---
development:
  dialect: "sqlite3"
  database: /home/muaddib/devs/buffalo/creaves_creaves_development.sqlite

test:
  dialect: "sqlite3"
  database: /home/muaddib/devs/buffalo/creaves_creaves_test.sqlite

production:
  dialect: "sqlite3"
  database: /home/muaddib/devs/buffalo/creaves_creaves_production.sqlite
