package actions

import (
	"creaves/models"
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v5"
	"github.com/gobuffalo/x/responder"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Animaltype)
// DB Table: Plural (animaltypes)
// Resource: Plural (Animaltypes)
// Path: Plural (/animaltypes)
// View Template Folder: Plural (/templates/animaltypes/)

// AnimaltypesResource is the resource for the Animaltype model
type AnimaltypesResource struct {
	buffalo.Resource
}

// List gets all Animaltypes. This function is mapped to the path
// GET /animaltypes
func (v AnimaltypesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	animaltypes := &models.Animaltypes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Animaltypes from the DB
	if err := q.All(animaltypes); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("animaltypes", animaltypes)
		return c.Render(http.StatusOK, r.HTML("/animaltypes/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(animaltypes))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(animaltypes))
	}).Respond(c)
}

// Show gets the data for one Animaltype. This function is mapped to
// the path GET /animaltypes/{animaltype_id}
func (v AnimaltypesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Animaltype
	animaltype := &models.Animaltype{}

	// To find the Animaltype the parameter animaltype_id is used.
	if err := tx.Find(animaltype, c.Param("animaltype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("animaltype", animaltype)

		return c.Render(http.StatusOK, r.HTML("/animaltypes/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(animaltype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(animaltype))
	}).Respond(c)
}

// New renders the form for creating a new Animaltype.
// This function is mapped to the path GET /animaltypes/new
func (v AnimaltypesResource) New(c buffalo.Context) error {
	c.Set("animaltype", &models.Animaltype{})

	return c.Render(http.StatusOK, r.HTML("/animaltypes/new.plush.html"))
}

// Create adds a Animaltype to the DB. This function is mapped to the
// path POST /animaltypes
func (v AnimaltypesResource) Create(c buffalo.Context) error {
	// Allocate an empty Animaltype
	animaltype := &models.Animaltype{}

	// Bind animaltype to the html form elements
	if err := c.Bind(animaltype); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(animaltype)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("animaltype", animaltype)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/animaltypes/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "animaltype.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/animaltypes/%v", animaltype.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(animaltype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(animaltype))
	}).Respond(c)
}

// Edit renders a edit form for a Animaltype. This function is
// mapped to the path GET /animaltypes/{animaltype_id}/edit
func (v AnimaltypesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Animaltype
	animaltype := &models.Animaltype{}

	if err := tx.Find(animaltype, c.Param("animaltype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("animaltype", animaltype)
	return c.Render(http.StatusOK, r.HTML("/animaltypes/edit.plush.html"))
}

// Update changes a Animaltype in the DB. This function is mapped to
// the path PUT /animaltypes/{animaltype_id}
func (v AnimaltypesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Animaltype
	animaltype := &models.Animaltype{}

	if err := tx.Find(animaltype, c.Param("animaltype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Animaltype to the html form elements
	if err := c.Bind(animaltype); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(animaltype)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("animaltype", animaltype)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/animaltypes/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "animaltype.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/animaltypes/%v", animaltype.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(animaltype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(animaltype))
	}).Respond(c)
}

// Destroy deletes a Animaltype from the DB. This function is mapped
// to the path DELETE /animaltypes/{animaltype_id}
func (v AnimaltypesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Animaltype
	animaltype := &models.Animaltype{}

	// To find the Animaltype the parameter animaltype_id is used.
	if err := tx.Find(animaltype, c.Param("animaltype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(animaltype); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "animaltype.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/animaltypes")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(animaltype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(animaltype))
	}).Respond(c)
}
