package actions

import (
	"encoding/json"
	"fmt"

	"creaves/models"
	"creaves/models/careplan"

	"github.com/gobuffalo/nulls"
	"github.com/gofrs/uuid"
)

// §7.4 seed library of docs/care-expert.md: 13 canonical matchers (SM1–SM13)
// and 12 rules (SR1–SR12), derived from the 2025/2026 production cohort.
// They ship as inactive drafts — except feeding-kind seeds, which ship
// active because the legacy `feeding_period` generator is frozen in the
// same boot (§8.1 step 3, no double-feed window exists).
//
// Four rules need a composite condition (SR1: SM1+weight, SR4: SM4+SM11,
// SR6: SM6+SM11, SR12: SM1 OR SM2). The care_rules schema references one
// matcher only, so each composite rule gets one derived matcher whose
// expression inlines the referenced seeds; they are clearly marked
// "(dérivé)" and are NOT part of the SM1–SM13 canonical set.

// ConverterTag marks rows generated by the startup converter so rollback
// can identify them (§8.2: "tagged created_by='care_plan_converter'").
const ConverterTag = "care_plan_converter"

// seedMatcherDef is one §7.4 seed matcher row.
type seedMatcherDef struct {
	Key        string // SM1..SM13 (or "SR1*" for derived)
	Name       string
	Expression string
	Derived    bool // true for the composite-rule matchers
}

// seedRuleDef is one §7.4 seed rule row. CaretypeName is resolved against
// the live caretypes table at conversion time; rules whose caretype is
// missing are skipped with a report line (payload needs a real id, §4.2).
type seedRuleDef struct {
	Key          string // SR1..SR12
	Name         string
	Kind         string
	MatcherKey   string // seedMatcherDef.Key
	CaretypeName string // "" = no caretype (cleanup/weighing)
	ScheduleJSON string
	PayloadFood  string
	ForceFeed    bool
	Drug         string
	Dosage       string
	DosageTable  bool
	Note         string
	Instructions string
	DurationDays int
}

// SeedMatchers returns the §7.4 seed matchers, canonical SM1–SM13 first.
func SeedMatchers() []seedMatcherDef {
	const herisson = `animal_type = "Hérissons / Insectivore"`
	return []seedMatcherDef{
		{Key: "SM1", Name: "Hérisson bébé", Expression: herisson + ` AND animal_age = "bébé"`},
		{Key: "SM2", Name: "Hérisson juvénile", Expression: herisson + ` AND animal_age = "juvénile"`},
		{Key: "SM3", Name: "Hérisson adulte", Expression: herisson + ` AND animal_age = "adulte"`},
		{Key: "SM4", Name: "Colombidés", Expression: `animal_type = "Colombidés"`},
		{Key: "SM5", Name: "Rapaces", Expression: `animal_type = "Rapaces"`},
		{Key: "SM6", Name: "Canidés", Expression: `animal_type = "Canidés"`},
		{Key: "SM7", Name: "Tiques à l'admission", Expression: `has_parasites = true AND parasites ~ "(?i)tiques"`},
		{Key: "SM8", Name: "Puces à l'admission", Expression: `has_parasites = true AND parasites ~ "(?i)puces"`},
		{Key: "SM9", Name: "Myiases à l'admission", Expression: `has_parasites = true AND parasites ~ "(?i)myiases|mouches plates|oeufs de mouche"`},
		{Key: "SM10", Name: "Blessés", Expression: `has_wounds = true`},
		{Key: "SM11", Name: "Bébé (tous types)", Expression: `animal_age = "bébé"`},
		{Key: "SM12", Name: "Juvénile (tous types)", Expression: `animal_age = "juvénile"`},
		{Key: "SM13", Name: "Gavage forcé", Expression: `force_feed = true`},
		// R8-3: zone-attribute field — occupied cages of "requires cleanup"
		// zones (zones.requires_cleanup) join the cleanup list.
		{Key: "SM14", Name: "Zone à nettoyer", Expression: `zone_requires_cleanup = true`},
		// Derived composite matchers (§7.4 SR1/SR4/SR6/SR12 conditions).
		{Key: "SR1*", Name: "Hérisson bébé < 300 g (dérivé SM1)", Derived: true,
			Expression: herisson + ` AND animal_age = "bébé" AND weight_g < 300`},
		{Key: "SR4*", Name: "Colombidés bébé (dérivé SM4+SM11)", Derived: true,
			Expression: `animal_type = "Colombidés" AND animal_age = "bébé"`},
		{Key: "SR6*", Name: "Canidés bébé (dérivé SM6+SM11)", Derived: true,
			Expression: `animal_type = "Canidés" AND animal_age = "bébé"`},
		{Key: "SR12*", Name: "Hérisson bébé ou juvénile (dérivé SM1 OU SM2)", Derived: true,
			Expression: herisson + ` AND (animal_age = "bébé" OR animal_age = "juvénile")`},
	}
}

// SeedRules returns the §7.4 seed rules SR1–SR12.
func SeedRules() []seedRuleDef {
	return []seedRuleDef{
		{Key: "SR1", Name: "Hérisson bébé — gavage", Kind: careplan.KindFeeding, MatcherKey: "SR1*",
			CaretypeName: "Repas", PayloadFood: "Croquettes + 4 VDF", ForceFeed: true,
			ScheduleJSON: `{"times":["07:00","09:30","12:30","15:30","19:00"],"every_days":1,"anchor":"intake","grace_minutes":45,"miss_after_hours":12}`},
		{Key: "SR2", Name: "Hérisson juvénile — repas 2x/j", Kind: careplan.KindFeeding, MatcherKey: "SM2",
			CaretypeName: "Repas", PayloadFood: "Croquettes + 4 VDF + EAU",
			ScheduleJSON: `{"times":["09:00","18:00"],"every_days":1,"anchor":"intake"}`},
		{Key: "SR3", Name: "Colombidés — grains AM/PM", Kind: careplan.KindFeeding, MatcherKey: "SM4",
			CaretypeName: "Alimentation", PayloadFood: "grains pigeons eau",
			ScheduleJSON: `{"times":["08:30","17:00"],"every_days":1,"anchor":"intake"}`},
		{Key: "SR4", Name: "Colombidés bébé — NB gavage", Kind: careplan.KindFeeding, MatcherKey: "SR4*",
			CaretypeName: "Repas", PayloadFood: "NB 1/2 50ml", ForceFeed: true,
			ScheduleJSON: `{"times":["08:00","11:00","14:00","17:00"],"every_days":1,"anchor":"intake"}`},
		{Key: "SR5", Name: "Rapaces — nourrissage", Kind: careplan.KindFeeding, MatcherKey: "SM5",
			CaretypeName: "Alimentation", PayloadFood: "poussins/souris selon régime",
			ScheduleJSON: `{"times":["08:00"],"every_days":1,"anchor":"intake"}`},
		{Key: "SR6", Name: "Canidés bébé — nourrissage groupe", Kind: careplan.KindFeeding, MatcherKey: "SR6*",
			CaretypeName: "Alimentation", Note: "Nourrissage groupe — voir régime admission",
			ScheduleJSON: `{"times":["08:00"],"every_days":1,"anchor":"intake"}`},
		{Key: "SR7", Name: "Tiques → Ivomec 5j", Kind: careplan.KindMedication, MatcherKey: "SM7",
			Drug: "Ivomec 1% (SC)", DosageTable: true, DurationDays: 5,
			Note:         "Contrôler tiques restantes au jour 5",
			ScheduleJSON: `{"times":["08:00"],"every_days":1,"anchor":"intake","duration_days":5}`},
		{Key: "SR8", Name: "Puces → Sarnacuran", Kind: careplan.KindMedication, MatcherKey: "SM8",
			Drug: "Sarnacuran", Dosage: "spray", DurationDays: 3,
			ScheduleJSON: `{"times":["08:00"],"every_days":1,"anchor":"intake","duration_days":3}`},
		{Key: "SR9", Name: "Nettoyage quotidien", Kind: careplan.KindCleanup, MatcherKey: "",
			Note:         "Nettoyage cage + eau fraîche",
			ScheduleJSON: `{"times":["09:00"],"every_days":1,"anchor":"intake","grace_minutes":180,"miss_after_hours":24}`},
		{Key: "SR10", Name: "Pesée hebdo juvéniles", Kind: careplan.KindWeighing, MatcherKey: "SM12",
			Note:         "Pesée de contrôle",
			ScheduleJSON: `{"times":["10:00"],"every_days":7,"anchor":"intake","grace_minutes":720}`},
		{Key: "SR11", Name: "Blessés — contrôle quotidien", Kind: careplan.KindCare, MatcherKey: "SM10",
			CaretypeName: "Soin", Instructions: "Contrôle plaie + bandage",
			ScheduleJSON: `{"times":["09:30"],"every_days":1,"anchor":"intake"}`},
		{Key: "SR12", Name: "Hérisson — Catosal + Réhydratation", Kind: careplan.KindMedication, MatcherKey: "SR12*",
			Drug: "Catosal 10%", DosageTable: true, DurationDays: 3,
			Note:         "+ Réhydratation (SC)",
			ScheduleJSON: `{"times":["08:00"],"every_days":1,"anchor":"intake","duration_days":3}`},
		// R8-3: general cleanup enforcement — every occupied cage of a zone
		// flagged "requires cleanup" gets a daily cleanup occurrence.
		{Key: "SR13", Name: "Nettoyage des cages occupées", Kind: careplan.KindCleanup, MatcherKey: "SM14",
			Note:         "Nettoyage cage + eau fraîche",
			ScheduleJSON: `{"times":["09:00"],"every_days":1,"anchor":"intake","grace_minutes":180,"miss_after_hours":24}`},
	}
}

// buildSeedMatcher materializes one seed matcher model (expression parse
// checked by Validate at save time).
func buildSeedMatcher(def seedMatcherDef) *models.CareMatcher {
	return &models.CareMatcher{
		Name:        def.Name,
		Description: nulls.NewString(fmt.Sprintf("Bibliothèque §7.4 %s [source: %s]", def.Key, ConverterTag)),
		Expression:  def.Expression,
	}
}

// buildSeedRule materializes one seed rule model. caretypeID resolved by
// the caller; feeding-kind seeds ship active (§8.1 step 1), everything
// else is an inactive draft for admin review.
func buildSeedRule(def seedRuleDef, matcherID uuid.NullUUID, caretypeID string) (*models.CareRule, error) {
	// R8-3: SR13 ENFORCES cleanup on flagged zones — it ships active (the
	// whole point of the rule); everything else stays an inactive draft.
	active := def.Kind == careplan.KindFeeding || def.Key == "SR13"
	r := &models.CareRule{
		Name:            def.Name,
		Description:     nulls.NewString(fmt.Sprintf("Bibliothèque §7.4 %s [source: %s]", def.Key, ConverterTag)),
		ActionKind:      def.Kind,
		ActionPayload:   buildSeedPayload(def, caretypeID),
		Schedule:        []byte(def.ScheduleJSON),
		MatcherID:       matcherID,
		Active:          active,
		StopOnOuttake:   true,
		LatchMembership: def.DurationDays > 0,
	}
	if verrs, err := r.Validate(nil); verrs.HasAny() || err != nil {
		return nil, fmt.Errorf("seed %s invalid: %v / %v", def.Key, verrs, err)
	}
	return r, nil
}

func buildSeedPayload(def seedRuleDef, caretypeID string) []byte {
	switch def.Kind {
	case careplan.KindFeeding:
		return []byte(marshalSeed(map[string]any{
			"caretype_id": caretypeID, "food": def.PayloadFood, "force_feed": def.ForceFeed, "note": def.Note,
		}))
	case careplan.KindMedication:
		m := map[string]any{"drug": def.Drug, "note": def.Note}
		if def.DosageTable {
			m["dosage_from_dosages_table"] = true
		} else {
			m["dosage"] = def.Dosage
		}
		return []byte(marshalSeed(m))
	case careplan.KindCare:
		return []byte(marshalSeed(map[string]any{
			"caretype_id": caretypeID, "instructions": def.Instructions, "note": def.Note,
		}))
	default: // cleanup / weighing: no required fields
		return []byte(marshalSeed(map[string]any{"note": def.Note}))
	}
}

func marshalSeed(m map[string]any) []byte {
	// encoding/json sorts map keys — deterministic output.
	b, err := json.Marshal(m)
	if err != nil {
		return []byte("{}")
	}
	return b
}
