package actions

import (
	"creaves/models"
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v5"
	"github.com/gobuffalo/x/responder"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Discoverer)
// DB Table: Plural (discoverers)
// Resource: Plural (Discoverers)
// Path: Plural (/discoverers)
// View Template Folder: Plural (/templates/discoverers/)

// DiscoverersResource is the resource for the Discoverer model
type DiscoverersResource struct {
	buffalo.Resource
}

// List gets all Discoverers. This function is mapped to the path
// GET /discoverers
func (v DiscoverersResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	discoverers := &models.Discoverers{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Discoverers from the DB
	if err := q.All(discoverers); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("discoverers", discoverers)
		return c.Render(http.StatusOK, r.HTML("/discoverers/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(discoverers))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(discoverers))
	}).Respond(c)
}

// FindByID returns the ressource by id
func (v DiscoverersResource) FindByID(c buffalo.Context, id string) (*models.Discoverer, error) {
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return nil, fmt.Errorf("no transaction found")
	}
	// Allocate an empty Discoverer
	discoverer := &models.Discoverer{}

	// To find the Discoverer the parameter discoverer_id is used.
	if err := tx.Find(discoverer, id); err != nil {
		return nil, c.Error(http.StatusNotFound, err)
	}

	return discoverer, nil
}

// Show gets the data for one Discoverer. This function is mapped to
// the path GET /discoverers/{discoverer_id}
func (v DiscoverersResource) Show(c buffalo.Context) error {
	discoverer, err := v.FindByID(c, c.Param("discoverer_id"))
	if err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("discoverer", discoverer)

		return c.Render(http.StatusOK, r.HTML("/discoverers/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(discoverer))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(discoverer))
	}).Respond(c)
}

// New renders the form for creating a new Discoverer.
// This function is mapped to the path GET /discoverers/new
func (v DiscoverersResource) New(c buffalo.Context) error {
	c.Set("discoverer", &models.Discoverer{})

	return c.Render(http.StatusOK, r.HTML("/discoverers/new.plush.html"))
}

// Create adds a Discoverer to the DB. This function is mapped to the
// path POST /discoverers
func (v DiscoverersResource) Create(c buffalo.Context) error {
	// Allocate an empty Discoverer
	discoverer := &models.Discoverer{}

	// Bind discoverer to the html form elements
	if err := c.Bind(discoverer); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(discoverer)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("discoverer", discoverer)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/discoverers/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "discoverer.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/discoverers/%v", discoverer.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(discoverer))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(discoverer))
	}).Respond(c)
}

// Edit renders a edit form for a Discoverer. This function is
// mapped to the path GET /discoverers/{discoverer_id}/edit
func (v DiscoverersResource) Edit(c buffalo.Context) error {
	discoverer, err := v.FindByID(c, c.Param("discoverer_id"))
	if err != nil {
		return err
	}

	c.Set("discoverer", discoverer)
	return c.Render(http.StatusOK, r.HTML("/discoverers/edit.plush.html"))
}

// Update changes a Discoverer in the DB. This function is mapped to
// the path PUT /discoverers/{discoverer_id}
func (v DiscoverersResource) Update(c buffalo.Context) error {
	discoverer, err := v.FindByID(c, c.Param("discoverer_id"))
	if err != nil {
		return err
	}

	// Bind Discoverer to the html form elements
	if err := c.Bind(discoverer); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	verrs, err := tx.ValidateAndUpdate(discoverer)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("discoverer", discoverer)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/discoverers/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "discoverer.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/discoverers/%v", discoverer.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(discoverer))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(discoverer))
	}).Respond(c)
}

// Destroy deletes a Discoverer from the DB. This function is mapped
// to the path DELETE /discoverers/{discoverer_id}
func (v DiscoverersResource) Destroy(c buffalo.Context) error {
	// Admin only
	if !GetCurrentUser(c).Admin {
		return c.Error(http.StatusForbidden, fmt.Errorf("restricted"))
	}

	discoverer, err := v.FindByID(c, c.Param("discoverer_id"))
	if err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	if err := tx.Destroy(discoverer); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "discoverer.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/discoverers")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(discoverer))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(discoverer))
	}).Respond(c)
}
