package actions

import (

  "fmt"
  "net/http"
  "github.com/gobuffalo/buffalo"
  "github.com/gobuffalo/pop/v5"
  "github.com/gobuffalo/x/responder"
  "creaves/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Drug)
// DB Table: Plural (drugs)
// Resource: Plural (Drugs)
// Path: Plural (/drugs)
// View Template Folder: Plural (/templates/drugs/)

// DrugsResource is the resource for the Drug model
type DrugsResource struct{
  buffalo.Resource
}

// List gets all Drugs. This function is mapped to the path
// GET /drugs
func (v DrugsResource) List(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  drugs := &models.Drugs{}

  // Paginate results. Params "page" and "per_page" control pagination.
  // Default values are "page=1" and "per_page=20".
  q := tx.PaginateFromParams(c.Params())

  // Retrieve all Drugs from the DB
  if err := q.All(drugs); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // Add the paginator to the context so it can be used in the template.
    c.Set("pagination", q.Paginator)

    c.Set("drugs", drugs)
    return c.Render(http.StatusOK, r.HTML("/drugs/index.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(drugs))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(drugs))
  }).Respond(c)
}

// Show gets the data for one Drug. This function is mapped to
// the path GET /drugs/{drug_id}
func (v DrugsResource) Show(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Drug
  drug := &models.Drug{}

  // To find the Drug the parameter drug_id is used.
  if err := tx.Find(drug, c.Param("drug_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    c.Set("drug", drug)

    return c.Render(http.StatusOK, r.HTML("/drugs/show.plush.html"))
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(200, r.JSON(drug))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(200, r.XML(drug))
  }).Respond(c)
}

// New renders the form for creating a new Drug.
// This function is mapped to the path GET /drugs/new
func (v DrugsResource) New(c buffalo.Context) error {
  c.Set("drug", &models.Drug{})

  return c.Render(http.StatusOK, r.HTML("/drugs/new.plush.html"))
}
// Create adds a Drug to the DB. This function is mapped to the
// path POST /drugs
func (v DrugsResource) Create(c buffalo.Context) error {
  // Allocate an empty Drug
  drug := &models.Drug{}

  // Bind drug to the html form elements
  if err := c.Bind(drug); err != nil {
    return err
  }

  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Validate the data from the html form
  verrs, err := tx.ValidateAndCreate(drug)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the new.html template that the user can
      // correct the input.
      c.Set("drug", drug)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/drugs/new.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "drug.created.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/drugs/%v", drug.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.JSON(drug))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusCreated, r.XML(drug))
  }).Respond(c)
}

// Edit renders a edit form for a Drug. This function is
// mapped to the path GET /drugs/{drug_id}/edit
func (v DrugsResource) Edit(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Drug
  drug := &models.Drug{}

  if err := tx.Find(drug, c.Param("drug_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  c.Set("drug", drug)
  return c.Render(http.StatusOK, r.HTML("/drugs/edit.plush.html"))
}
// Update changes a Drug in the DB. This function is mapped to
// the path PUT /drugs/{drug_id}
func (v DrugsResource) Update(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Drug
  drug := &models.Drug{}

  if err := tx.Find(drug, c.Param("drug_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  // Bind Drug to the html form elements
  if err := c.Bind(drug); err != nil {
    return err
  }

  verrs, err := tx.ValidateAndUpdate(drug)
  if err != nil {
    return err
  }

  if verrs.HasAny() {
    return responder.Wants("html", func (c buffalo.Context) error {
      // Make the errors available inside the html template
      c.Set("errors", verrs)

      // Render again the edit.html template that the user can
      // correct the input.
      c.Set("drug", drug)

      return c.Render(http.StatusUnprocessableEntity, r.HTML("/drugs/edit.plush.html"))
    }).Wants("json", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
    }).Wants("xml", func (c buffalo.Context) error {
      return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
    }).Respond(c)
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a success message
    c.Flash().Add("success", T.Translate(c, "drug.updated.success"))

    // and redirect to the show page
    return c.Redirect(http.StatusSeeOther, "/drugs/%v", drug.ID)
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(drug))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(drug))
  }).Respond(c)
}

// Destroy deletes a Drug from the DB. This function is mapped
// to the path DELETE /drugs/{drug_id}
func (v DrugsResource) Destroy(c buffalo.Context) error {
  // Get the DB connection from the context
  tx, ok := c.Value("tx").(*pop.Connection)
  if !ok {
    return fmt.Errorf("no transaction found")
  }

  // Allocate an empty Drug
  drug := &models.Drug{}

  // To find the Drug the parameter drug_id is used.
  if err := tx.Find(drug, c.Param("drug_id")); err != nil {
    return c.Error(http.StatusNotFound, err)
  }

  if err := tx.Destroy(drug); err != nil {
    return err
  }

  return responder.Wants("html", func (c buffalo.Context) error {
    // If there are no errors set a flash message
    c.Flash().Add("success", T.Translate(c, "drug.destroyed.success"))

    // Redirect to the index page
    return c.Redirect(http.StatusSeeOther, "/drugs")
  }).Wants("json", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.JSON(drug))
  }).Wants("xml", func (c buffalo.Context) error {
    return c.Render(http.StatusOK, r.XML(drug))
  }).Respond(c)
}
