package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"creaves/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Locality)
// DB Table: Plural (localities)
// Resource: Plural (Localities)
// Path: Plural (/localities)
// View Template Folder: Plural (/templates/localities/)

// LocalitiesResource is the resource for the Locality model
type LocalitiesResource struct {
	buffalo.Resource
}

// List gets all Localities. This function is mapped to the path
// GET /localities
func (v LocalitiesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	localities := &models.Localities{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params()).Order("Country ASC, Region ASC, Province ASC, Municipality ASC")

	// Retrieve all Localities from the DB
	if err := q.All(localities); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("localities", localities)
		return c.Render(http.StatusOK, r.HTML("localities/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(localities))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(localities))
	}).Respond(c)
}

// Show gets the data for one Locality. This function is mapped to
// the path GET /localities/{locality_id}
func (v LocalitiesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Locality
	locality := &models.Locality{}

	// To find the Locality the parameter locality_id is used.
	if err := tx.Find(locality, c.Param("locality_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("locality", locality)

		return c.Render(http.StatusOK, r.HTML("localities/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(locality))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(locality))
	}).Respond(c)
}

// New renders the form for creating a new Locality.
// This function is mapped to the path GET /localities/new
func (v LocalitiesResource) New(c buffalo.Context) error {
	c.Set("locality", &models.Locality{})

	return c.Render(http.StatusOK, r.HTML("localities/new.plush.html"))
}

// Create adds a Locality to the DB. This function is mapped to the
// path POST /localities
func (v LocalitiesResource) Create(c buffalo.Context) error {
	// Allocate an empty Locality
	locality := &models.Locality{}

	// Bind locality to the html form elements
	if err := c.Bind(locality); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(locality)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("locality", locality)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("localities/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "locality.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/localities/%v", locality.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(locality))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(locality))
	}).Respond(c)
}

// Edit renders a edit form for a Locality. This function is
// mapped to the path GET /localities/{locality_id}/edit
func (v LocalitiesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Locality
	locality := &models.Locality{}

	if err := tx.Find(locality, c.Param("locality_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("locality", locality)
	return c.Render(http.StatusOK, r.HTML("localities/edit.plush.html"))
}

// Update changes a Locality in the DB. This function is mapped to
// the path PUT /localities/{locality_id}
func (v LocalitiesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Locality
	locality := &models.Locality{}

	if err := tx.Find(locality, c.Param("locality_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Locality to the html form elements
	if err := c.Bind(locality); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(locality)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("locality", locality)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("localities/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "locality.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/localities/%v", locality.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(locality))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(locality))
	}).Respond(c)
}

// Destroy deletes a Locality from the DB. This function is mapped
// to the path DELETE /localities/{locality_id}
func (v LocalitiesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Locality
	locality := &models.Locality{}

	// To find the Locality the parameter locality_id is used.
	if err := tx.Find(locality, c.Param("locality_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(locality); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "locality.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/localities")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(locality))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(locality))
	}).Respond(c)
}
