package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"creaves/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (NativeStatus)
// DB Table: Plural (native_statuses)
// Resource: Plural (NativeStatuses)
// Path: Plural (/native_statuses)
// View Template Folder: Plural (/templates/native_statuses/)

// NativeStatusesResource is the resource for the NativeStatus model
type NativeStatusesResource struct {
	buffalo.Resource
}

// List gets all NativeStatuses. This function is mapped to the path
// GET /native_statuses
func (v NativeStatusesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	nativeStatuses := &models.NativeStatuses{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all NativeStatuses from the DB
	if err := q.All(nativeStatuses); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("nativeStatuses", nativeStatuses)
		return c.Render(http.StatusOK, r.HTML("native_statuses/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(nativeStatuses))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(nativeStatuses))
	}).Respond(c)
}

// Show gets the data for one NativeStatus. This function is mapped to
// the path GET /native_statuses/{native_status_id}
func (v NativeStatusesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty NativeStatus
	nativeStatus := &models.NativeStatus{}

	// To find the NativeStatus the parameter native_status_id is used.
	if err := tx.Find(nativeStatus, c.Param("native_status_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("nativeStatus", nativeStatus)

		return c.Render(http.StatusOK, r.HTML("native_statuses/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(nativeStatus))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(nativeStatus))
	}).Respond(c)
}

// New renders the form for creating a new NativeStatus.
// This function is mapped to the path GET /native_statuses/new
func (v NativeStatusesResource) New(c buffalo.Context) error {
	c.Set("nativeStatus", &models.NativeStatus{})

	return c.Render(http.StatusOK, r.HTML("native_statuses/new.plush.html"))
}

// Create adds a NativeStatus to the DB. This function is mapped to the
// path POST /native_statuses
func (v NativeStatusesResource) Create(c buffalo.Context) error {
	// Allocate an empty NativeStatus
	nativeStatus := &models.NativeStatus{}

	// Bind nativeStatus to the html form elements
	if err := c.Bind(nativeStatus); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(nativeStatus)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("nativeStatus", nativeStatus)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("native_statuses/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "nativeStatus.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/native_statuses/%v", nativeStatus.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(nativeStatus))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(nativeStatus))
	}).Respond(c)
}

// Edit renders a edit form for a NativeStatus. This function is
// mapped to the path GET /native_statuses/{native_status_id}/edit
func (v NativeStatusesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty NativeStatus
	nativeStatus := &models.NativeStatus{}

	if err := tx.Find(nativeStatus, c.Param("native_status_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("nativeStatus", nativeStatus)
	return c.Render(http.StatusOK, r.HTML("native_statuses/edit.plush.html"))
}

// Update changes a NativeStatus in the DB. This function is mapped to
// the path PUT /native_statuses/{native_status_id}
func (v NativeStatusesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty NativeStatus
	nativeStatus := &models.NativeStatus{}

	if err := tx.Find(nativeStatus, c.Param("native_status_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind NativeStatus to the html form elements
	if err := c.Bind(nativeStatus); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(nativeStatus)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("nativeStatus", nativeStatus)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("native_statuses/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "nativeStatus.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/native_statuses/%v", nativeStatus.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(nativeStatus))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(nativeStatus))
	}).Respond(c)
}

// Destroy deletes a NativeStatus from the DB. This function is mapped
// to the path DELETE /native_statuses/{native_status_id}
func (v NativeStatusesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty NativeStatus
	nativeStatus := &models.NativeStatus{}

	// To find the NativeStatus the parameter native_status_id is used.
	if err := tx.Find(nativeStatus, c.Param("native_status_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(nativeStatus); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "nativeStatus.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/native_statuses")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(nativeStatus))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(nativeStatus))
	}).Respond(c)
}
