package actions

import (
	"creaves/models"
	"encoding/json"
	"fmt"
	"html/template"
	"net/http"
	"time"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/nulls"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Outtake)
// DB Table: Plural (outtakes)
// Resource: Plural (Outtakes)
// Path: Plural (/outtakes)
// View Template Folder: Plural (/templates/outtakes/)

// OuttakesResource is the resource for the Outtake model
type OuttakesResource struct {
	buffalo.Resource
}

// List gets all Outtakes. This function is mapped to the path
// GET /outtakes
func (v OuttakesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	outtakes := &models.Outtakes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.Eager().PaginateFromParams(c.Params())

	// Retrieve all Outtakes from the DB
	if err := q.Order("date desc").All(outtakes); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("outtakes", outtakes)
		return c.Render(http.StatusOK, r.HTML("/outtakes/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(outtakes))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(outtakes))
	}).Respond(c)
}

// Show gets the data for one Outtake. This function is mapped to
// the path GET /outtakes/{outtake_id}
func (v OuttakesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Outtake
	outtake := &models.Outtake{}

	// To find the Outtake the parameter outtake_id is used.
	if err := tx.Eager().Find(outtake, c.Param("outtake_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}
	if _, err := EnrichAnimal(&outtake.Animal, c); err != nil {
		return c.Error(http.StatusInternalServerError, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("outtake", outtake)

		return c.Render(http.StatusOK, r.HTML("/outtakes/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(outtake))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(outtake))
	}).Respond(c)
}

// speciesNativeStatus returns the native status ID of the species matching
// the animal's species name, or "" when unknown.
func speciesNativeStatus(tx *pop.Connection, speciesName string) string {
	if speciesName == "" {
		return ""
	}
	species := &models.Species{}
	if err := tx.RawQuery("SELECT ID AS id, species, creaves_species, class, `order`, family, native_status, agw_group, subside_group, game, huntable, created_at, updated_at FROM species WHERE creaves_species = ?", speciesName).First(species); err != nil {
		return ""
	}
	return species.NativeStatus
}

// filterOuttaketypesForNativeStatus returns the subset of outtake types that
// are allowed for a species with the given native status. An empty native
// status disables filtering (unknown species → all types).
func filterOuttaketypesForNativeStatus(ts *models.Outtaketypes, nativeStatus string) *models.Outtaketypes {
	if nativeStatus == "" {
		return ts
	}
	res := models.Outtaketypes{}
	for _, t := range *ts {
		if !t.ExcludesNativeStatus(nativeStatus) {
			res = append(res, t)
		}
	}
	return &res
}

// setOuttakeLocationFormData passes to the template, as JSON script tags, the
// per-type location mode and the (translated) location options used by the
// new-outtake form JS.
func setOuttakeLocationFormData(c buffalo.Context, tx *pop.Connection, ts *models.Outtaketypes) error {
	modes := map[string]string{}
	for _, t := range *ts {
		modes[t.ID.String()] = t.LocationMode
	}
	modesJSON, err := json.Marshal(modes)
	if err != nil {
		return err
	}
	c.Set("outtakeLocationModesJSON", template.HTML(modesJSON))

	options := &models.OuttakeLocationOptions{}
	if err := tx.Order("name asc").All(options); err != nil {
		return err
	}
	ids := make([]string, 0, len(*options))
	for _, o := range *options {
		ids = append(ids, o.ID.String())
	}
	tr := translateIDs(tx, "outtake_location_options", "name", currentLang(c), ids)
	type optionEntry struct {
		Value string `json:"value"`
		Label string `json:"label"`
	}
	entries := make([]optionEntry, 0, len(*options))
	for _, o := range *options {
		entries = append(entries, optionEntry{
			Value: o.Name,
			Label: models.ResolveName(currentLang(c), o.Name, tr, o.ID.String()),
		})
	}
	optionsJSON, err := json.Marshal(entries)
	if err != nil {
		return err
	}
	c.Set("outtakeLocationOptionsJSON", template.HTML(optionsJSON))
	return nil
}

// setFilteredOuttakeFormData sets selectOuttaketype (filtered by the species
// native status of the animal) plus the location-mode JSON data used by the
// new-outtake form JS.
func setFilteredOuttakeFormData(c buffalo.Context, tx *pop.Connection, ot *models.Outtaketypes, animal *models.Animal) error {
	filtered := filterOuttaketypesForNativeStatus(ot, speciesNativeStatus(tx, animal.Species))
	c.Set("selectOuttaketype", outtakeTypesToSelectables(filtered, currentLang(c), tx))
	return setOuttakeLocationFormData(c, tx, filtered)
}

// enforceOuttakeLocationRule applies the location_mode of the outtake type to
// the bound outtake: "none" clears the location, "list" requires the value to
// be one of the reference options (matched on the base name), "free" accepts
// any value. It returns an error when the rule is violated.
func enforceOuttakeLocationRule(tx *pop.Connection, outtake *models.Outtake, outtakeType *models.Outtaketype) error {
	// The precise address ("Adresse, lieu précis", #197-4) only applies to
	// free-mode types; clear it for the other modes, mirroring Location.
	if outtakeType.LocationMode != models.OuttakeLocationModeFree {
		outtake.PreciseLocation = nulls.String{}
	}
	switch outtakeType.LocationMode {
	case models.OuttakeLocationModeNone, "":
		outtake.Location = nulls.String{}
		return nil
	case models.OuttakeLocationModeList:
		if !outtake.Location.Valid || outtake.Location.String == "" {
			return fmt.Errorf("location is required for outcome type %s", outtakeType.Name)
		}
		count, err := tx.Where("name = ?", outtake.Location.String).Count(&models.OuttakeLocationOption{})
		if err != nil {
			return err
		}
		if count == 0 {
			return fmt.Errorf("location %q is not in the reference list", outtake.Location.String)
		}
		return nil
	default:
		// free mode: any text is accepted
		return nil
	}
}

// New renders the form for creating a new Outtake.
// This function is mapped to the path GET /outtakes/new
func (v OuttakesResource) New(c buffalo.Context) error {
	outtake := &models.Outtake{
		Date: time.Now(),
	}
	c.Set("outtake", outtake)
	// Intake date of the animal being taken out, for the stay-duration
	// helpers in the form (issue #175). Empty while no animal is picked.
	c.Set("intakeDate", "")

	// Set outtake type
	ot, err := outtakeTypes(c)
	if err != nil {
		return err
	}
	c.Set("selectOuttaketype", outtakeTypesToSelectables(ot, currentLang(c), c.Value("tx").(*pop.Connection)))

	animalYearNumber := c.Param("animal_year_number")
	if len(animalYearNumber) > 0 {
		// Get the DB connection from the context
		tx, ok := c.Value("tx").(*pop.Connection)
		if !ok {
			return fmt.Errorf("no transaction found")
		}

		animal := &models.Animal{}
		errCode := http.StatusOK

		// for message
		data := map[string]interface{}{
			"animalID": animalYearNumber,
		}

		c.Logger().Debug("animalYearNumber:", animalYearNumber)
		matches := AnimalYearNumberRegEx.FindStringSubmatch(animalYearNumber)
		if matches == nil {
			return fmt.Errorf("invalid year number: %s", animalYearNumber)
		}
		c.Logger().Debug("animalYearNumber regex matches:", matches)
		q := tx.Where("yearNumber = ?", matches[1])
		if len(matches) == 4 && len(matches[3]) == 2 {
			q = q.Where("year = ?", fmt.Sprintf("20%s", matches[3]))
		}

		err := q.Order("ID desc").Eager().First(animal)
		if err != nil {
			c.Logger().Debug("Error:", err)
			c.Flash().Add("danger", T.Translate(c, "outtake.animal.not.found", data))
			errCode = http.StatusNotFound
		}

		//c.Logger().Debugf("Loaded animal %v", animal)

		if animal.Outtake != nil {
			c.Flash().Add("danger", T.Translate(c, "outtake.animal.outtake.already.exist", data))
			errCode = http.StatusConflict
		}
		if errCode != http.StatusOK {
			return c.Render(errCode, r.HTML("/outtakes/new.plush.html"))
		}
		animal.Outtake = outtake
		c.Set("animal", animal)
		c.Set("intakeDate", animal.Intake.Date.Format(models.DateTimeFormat))

		// Filter out outcome types forbidden by the species native status
		// and expose the location-mode data for the form JS.
		if err := setFilteredOuttakeFormData(c, tx, ot, animal); err != nil {
			return err
		}
	}

	return c.Render(http.StatusOK, r.HTML("/outtakes/new.plush.html"))
}

// renderOuttakeNewRejected re-renders the new-outtake form (422) with the
// animal context, the filtered outcome type list and the location-mode data
// so the user can correct the input.
func renderOuttakeNewRejected(c buffalo.Context, tx *pop.Connection, animal *models.Animal, outtake *models.Outtake) error {
	ot, err := outtakeTypes(c)
	if err != nil {
		return err
	}
	c.Set("outtake", outtake)
	c.Set("animal", animal)
	c.Set("intakeDate", animal.Intake.Date.Format(models.DateTimeFormat))
	if err := setFilteredOuttakeFormData(c, tx, ot, animal); err != nil {
		return err
	}
	return c.Render(http.StatusUnprocessableEntity, r.HTML("/outtakes/new.plush.html"))
}

// rejectOuttakeCreate checks the outtake rules for the bound outtake: the
// outcome type must exist and be allowed for the species native status, and
// the location must satisfy the type's location_mode. On violation it adds a
// translated flash and re-renders the form with 422; it reports whether the
// request was rejected.
func rejectOuttakeCreate(c buffalo.Context, tx *pop.Connection, animal *models.Animal, outtake *models.Outtake) (bool, error) {
	// No outtake date in the future (issue #175). The bound date is a naive
	// local wall clock (binder parses as UTC) — compare in the same frame.
	if outtake.Date.After(models.FormWallClockNow().Add(time.Minute)) {
		c.Flash().Add("danger", T.Translate(c, "outtake.date.future"))
		return true, renderOuttakeNewRejected(c, tx, animal, outtake)
	}
	outtakeType := &models.Outtaketype{}
	if err := tx.Find(outtakeType, outtake.TypeID); err != nil {
		c.Flash().Add("danger", T.Translate(c, "outtake.type.invalid"))
		return true, renderOuttakeNewRejected(c, tx, animal, outtake)
	}
	if outtakeType.ExcludesNativeStatus(speciesNativeStatus(tx, animal.Species)) {
		c.Flash().Add("danger", T.Translate(c, "outtake.type.forbidden_by_native_status"))
		return true, renderOuttakeNewRejected(c, tx, animal, outtake)
	}
	if err := enforceOuttakeLocationRule(tx, outtake, outtakeType); err != nil {
		c.Flash().Add("danger", T.Translate(c, "outtake.location.invalid"))
		return true, renderOuttakeNewRejected(c, tx, animal, outtake)
	}
	return false, nil
}

// Create adds a Outtake to the DB. This function is mapped to the
// path POST /outtakes
func (v OuttakesResource) Create(c buffalo.Context) error {
	// Allocate an empty Outtake
	outtake := &models.Outtake{}

	// Bind outtake to the html form elements
	if err := c.Bind(outtake); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	animalID := c.Param("animal_id")
	if len(animalID) <= 0 {
		return fmt.Errorf("missing animal ID")
	}
	animal := &models.Animal{}
	if err := tx.Eager().Find(animal, animalID); err != nil {
		// cannot link animal
		return c.Render(http.StatusNotFound, r.HTML("/outtakes/new.plush.html"))
	}

	// Enforce outtake rules: the outcome type must be allowed for the
	// species native status, and the location must match the type mode.
	if rejected, err := rejectOuttakeCreate(c, tx, animal, outtake); rejected || err != nil {
		return err
	}
	// Persist the stay duration from the intake date to the outtake date
	// (issue #175).
	outtake.ComputeStayDuration(animal.Intake.Date)
	// Audit snapshot before mutating the animal (ring, outtake link).
	oldAnimal := *animal
	// save ring if needed
	animalRing := c.Param(("animal_ring"))
	if animalRing != animal.Ring.String {
		animal.Ring = nulls.NewString(animalRing)
		c.Logger().Debugf("Seting up ring %v", animal.Ring)
		if err := tx.Update(animal); err != nil {
			return err
		}
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(outtake)
	if err != nil {
		return err
	}
	// Update animal if outtake is saved
	if !verrs.HasAny() {
		// Treatments scheduled after the outtake date are deleted: audit
		// them before the raw delete removes the records.
		deletedTreatments := models.Treatments{}
		if err := tx.Where("animal_id = ? and date >= ?", animalID, outtake.Date).All(&deletedTreatments); err != nil {
			return err
		}

		animal.OuttakeID = nulls.NewUUID(outtake.ID)
		animal.Outtake = outtake
		if err := tx.Update(animal); err != nil {
			return err
		}
		if err := tx.RawQuery("DELETE FROM treatments WHERE animal_id = ? and date >= ?",
			animalID,
			outtake.Date).Exec(); err != nil {
			return err
		}

		// Audit log: outtake creation + animal link/ring update (best effort)
		auditAnimalChange(c, tx, animal.ID, models.AuditEntityOuttake, auditEntityID(outtake.ID), models.AuditActionCreate, nil, auditOuttakeProjection(*outtake))
		auditAnimalChange(c, tx, animal.ID, models.AuditEntityAnimal, auditEntityID(animal.ID), models.AuditActionUpdate, auditAnimalProjection(oldAnimal), auditAnimalProjection(*animal))
		for i := range deletedTreatments {
			auditAnimalChange(c, tx, animal.ID, models.AuditEntityTreatment, auditEntityID(deletedTreatments[i].ID), models.AuditActionDelete, auditTreatmentProjection(deletedTreatments[i]), nil)
		}

		// Publish event based on outtake type
		if err := tx.Find(&outtake.Type, outtake.TypeID); err == nil {
			animal.Outtake = outtake
			if outtake.Type.Error {
				if err := PublishAnimalDiedEvent(tx, animal, GetCurrentUser(c)); err != nil {
					c.Logger().Warnf("Failed to publish animal_died event: %v", err)
				}
			} else {
				if err := PublishAnimalReleasedEvent(tx, animal, GetCurrentUser(c)); err != nil {
					c.Logger().Warnf("Failed to publish animal_released event: %v", err)
				}
			}
		}
		// Full-state event: outtake fields + CurrentStatus are part of the
		// canonical state hash.
		publishAnimalStateEventWarn(c, tx, animal.ID)
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Re-render the new.html form with the animal context and the
			// filtered outcome type list so the user can correct the input.
			return renderOuttakeNewRejected(c, tx, animal, outtake)
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	// Annual statistics tables count outtakes: drop the per-year cache.
	InvalidateAnnualStatsCache()

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "outtake.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/animals/%v/#nav-outtake", animalID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(outtake))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(outtake))
	}).Respond(c)
}

// Edit renders a edit form for a Outtake. This function is
// mapped to the path GET /outtakes/{outtake_id}/edit
func (v OuttakesResource) Edit(c buffalo.Context) error {
	// Admin only
	if !GetCurrentUser(c).Admin {
		return c.Error(http.StatusForbidden, fmt.Errorf("restricted"))
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Outtake
	outtake := &models.Outtake{}

	if err := tx.Eager().Find(outtake, c.Param("outtake_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}
	if _, err := EnrichAnimal(&outtake.Animal, c); err != nil {
		return c.Error(http.StatusInternalServerError, err)
	}
	c.Set("outtake", outtake)

	// Intake date of the animal for the stay-duration helpers (issue #175).
	c.Set("intakeDate", "")
	stayedAnimal := &models.Animal{}
	if err := tx.Eager().Where("outtake_id = ?", outtake.ID).First(stayedAnimal); err == nil && stayedAnimal.ID != 0 {
		c.Set("intakeDate", stayedAnimal.Intake.Date.Format(models.DateTimeFormat))
	}

	// Set outtake type
	ot, err := outtakeTypes(c)
	if err != nil {
		return err
	}
	c.Set("selectOuttaketype", outtakeTypesToSelectables(ot, currentLang(c), c.Value("tx").(*pop.Connection)))

	return c.Render(http.StatusOK, r.HTML("/outtakes/edit.plush.html"))
}

// Update changes a Outtake in the DB. This function is mapped to
// the path PUT /outtakes/{outtake_id}
func (v OuttakesResource) Update(c buffalo.Context) error {
	// Admin only
	if !GetCurrentUser(c).Admin {
		return c.Error(http.StatusForbidden, fmt.Errorf("restricted"))
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Outtake
	outtake := &models.Outtake{}

	if err := tx.Eager().Find(outtake, c.Param("outtake_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Audit snapshot before binding mutates the record.
	oldOuttake := *outtake

	// Bind Outtake to the html form elements
	if err := c.Bind(outtake); err != nil {
		return err
	}

	// Recompute the stay duration from the animal intake date to the new
	// outtake date (issue #175).
	stayedAnimal := &models.Animal{}
	if err := tx.Eager().Where("outtake_id = ?", outtake.ID).First(stayedAnimal); err == nil && stayedAnimal.ID != 0 {
		outtake.ComputeStayDuration(stayedAnimal.Intake.Date)
	}

	verrs, err := tx.ValidateAndUpdate(outtake)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("outtake", outtake)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/outtakes/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	// Audit log: outtake update (best effort). Outtake has no animal_id
	// column: resolve the concerned animal explicitly.
	auditedAnimal := &models.Animal{}
	if err := tx.Where("outtake_id = ?", outtake.ID).First(auditedAnimal); err == nil && auditedAnimal.ID != 0 {
		auditAnimalChange(c, tx, auditedAnimal.ID, models.AuditEntityOuttake, auditEntityID(outtake.ID), models.AuditActionUpdate, auditOuttakeProjection(oldOuttake), auditOuttakeProjection(*outtake))
		// Outtake fields are part of the canonical state hash.
		publishAnimalStateEventWarn(c, tx, auditedAnimal.ID)
	}

	// Annual statistics tables count outtakes: drop the per-year cache.
	InvalidateAnnualStatsCache()

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "outtake.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/outtakes/%v", outtake.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(outtake))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(outtake))
	}).Respond(c)
}

// Destroy deletes a Outtake from the DB. This function is mapped
// to the path DELETE /outtakes/{outtake_id}
func (v OuttakesResource) Destroy(c buffalo.Context) error {
	// Admin only
	if !GetCurrentUser(c).Admin {
		return c.Error(http.StatusForbidden, fmt.Errorf("restricted"))
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Outtake
	outtake := &models.Outtake{}

	// To find the Outtake the parameter outtake_id is used.
	if err := tx.Eager().Find(outtake, c.Param("outtake_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Unlink animal
	animal := &models.Animal{}
	if err := tx.Where("outtake_id = ?", outtake.ID).First(animal); err != nil {
		return err
	}

	// Audit snapshots before unlinking/destroying.
	oldAnimal := *animal

	animal.OuttakeID = nulls.UUID{}
	if err := tx.Update(animal); err != nil {
		return err
	}

	// destroy
	if err := tx.Destroy(outtake); err != nil {
		return err
	}

	// Audit log: outtake deletion + animal unlink (best effort)
	auditAnimalChange(c, tx, animal.ID, models.AuditEntityOuttake, auditEntityID(outtake.ID), models.AuditActionDelete, auditOuttakeProjection(*outtake), nil)
	auditAnimalChange(c, tx, animal.ID, models.AuditEntityAnimal, auditEntityID(animal.ID), models.AuditActionUpdate, auditAnimalProjection(oldAnimal), auditAnimalProjection(*animal))
	// Outtake removal reverts the animal to in_care; sync the new state.
	publishAnimalStateEventWarn(c, tx, animal.ID)

	// Annual statistics tables count outtakes: drop the per-year cache.
	InvalidateAnnualStatsCache()

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "outtake.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/outtakes")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(outtake))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(outtake))
	}).Respond(c)
}
