package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"creaves/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (OuttakeLocationOption)
// DB Table: Plural (outtake_location_options)
// Resource: Plural (OuttakeLocationOptions)
// Path: Plural (/outtake_location_options)
// View Template Folder: Plural (/templates/outtake_location_options/)

// OuttakeLocationOptionsResource is the resource for the OuttakeLocationOption model
type OuttakeLocationOptionsResource struct {
	buffalo.Resource
}

// List gets all OuttakeLocationOptions. This function is mapped to the path
// GET /outtake_location_options
func (v OuttakeLocationOptionsResource) List(c buffalo.Context) error {
	if _, err := requireMaintainer(c); err != nil {
		return err
	}
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	outtakeLocationOptions := &models.OuttakeLocationOptions{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all OuttakeLocationOptions from the DB
	if err := q.Order("name asc").All(outtakeLocationOptions); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("outtakeLocationOptions", outtakeLocationOptions)
		return c.Render(http.StatusOK, r.HTML("outtake_location_options/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(outtakeLocationOptions))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(outtakeLocationOptions))
	}).Respond(c)
}

// Show gets the data for one OuttakeLocationOption. This function is mapped to
// the path GET /outtake_location_options/{outtake_location_option_id}
func (v OuttakeLocationOptionsResource) Show(c buffalo.Context) error {
	if _, err := requireMaintainer(c); err != nil {
		return err
	}
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty OuttakeLocationOption
	outtakeLocationOption := &models.OuttakeLocationOption{}

	// To find the OuttakeLocationOption the parameter outtake_location_option_id is used.
	if err := tx.Find(outtakeLocationOption, c.Param("outtake_location_option_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("outtakeLocationOption", outtakeLocationOption)

		return c.Render(http.StatusOK, r.HTML("outtake_location_options/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(outtakeLocationOption))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(outtakeLocationOption))
	}).Respond(c)
}

// New renders the form for creating a new OuttakeLocationOption.
// This function is mapped to the path GET /outtake_location_options/new
func (v OuttakeLocationOptionsResource) New(c buffalo.Context) error {
	if _, err := requireMaintainer(c); err != nil {
		return err
	}
	c.Set("outtakeLocationOption", &models.OuttakeLocationOption{})

	if err := setTranslationValues(c, c.Value("tx").(*pop.Connection), "outtake_location_options", "", []string{"name"}); err != nil {
		return err
	}

	return c.Render(http.StatusOK, r.HTML("outtake_location_options/new.plush.html"))
}

// Create adds a OuttakeLocationOption to the DB. This function is mapped to the
// path POST /outtake_location_options
func (v OuttakeLocationOptionsResource) Create(c buffalo.Context) error {
	if _, err := requireMaintainer(c); err != nil {
		return err
	}
	// Allocate an empty OuttakeLocationOption
	outtakeLocationOption := &models.OuttakeLocationOption{}

	// Bind outtakeLocationOption to the html form elements
	if err := c.Bind(outtakeLocationOption); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(outtakeLocationOption)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("outtakeLocationOption", outtakeLocationOption)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("outtake_location_options/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	if err := saveTranslations(c, tx, "outtake_location_options", outtakeLocationOption.ID.String(), []string{"name"}); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "outtakeLocationOption.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/outtake_location_options/%v", outtakeLocationOption.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(outtakeLocationOption))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(outtakeLocationOption))
	}).Respond(c)
}

// Edit renders a edit form for a OuttakeLocationOption. This function is
// mapped to the path GET /outtake_location_options/{outtake_location_option_id}/edit
func (v OuttakeLocationOptionsResource) Edit(c buffalo.Context) error {
	if _, err := requireMaintainer(c); err != nil {
		return err
	}
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty OuttakeLocationOption
	outtakeLocationOption := &models.OuttakeLocationOption{}

	if err := tx.Find(outtakeLocationOption, c.Param("outtake_location_option_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("outtakeLocationOption", outtakeLocationOption)
	if err := setTranslationValues(c, tx, "outtake_location_options", outtakeLocationOption.ID.String(), []string{"name"}); err != nil {
		return err
	}
	return c.Render(http.StatusOK, r.HTML("outtake_location_options/edit.plush.html"))
}

// Update changes a OuttakeLocationOption in the DB. This function is mapped to
// the path PUT /outtake_location_options/{outtake_location_option_id}
func (v OuttakeLocationOptionsResource) Update(c buffalo.Context) error {
	if _, err := requireMaintainer(c); err != nil {
		return err
	}
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty OuttakeLocationOption
	outtakeLocationOption := &models.OuttakeLocationOption{}

	if err := tx.Find(outtakeLocationOption, c.Param("outtake_location_option_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind OuttakeLocationOption to the html form elements
	if err := c.Bind(outtakeLocationOption); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(outtakeLocationOption)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("outtakeLocationOption", outtakeLocationOption)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("outtake_location_options/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	if err := saveTranslations(c, tx, "outtake_location_options", outtakeLocationOption.ID.String(), []string{"name"}); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "outtakeLocationOption.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/outtake_location_options/%v", outtakeLocationOption.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(outtakeLocationOption))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(outtakeLocationOption))
	}).Respond(c)
}

// Destroy deletes a OuttakeLocationOption from the DB. This function is mapped
// to the path DELETE /outtake_location_options/{outtake_location_option_id}.
// Outtakes store the location as plain text, so existing records keep the
// deleted name as historical text — no remap flow is required.
func (v OuttakeLocationOptionsResource) Destroy(c buffalo.Context) error {
	if _, err := requireMaintainer(c); err != nil {
		return err
	}
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty OuttakeLocationOption
	outtakeLocationOption := &models.OuttakeLocationOption{}

	// To find the OuttakeLocationOption the parameter outtake_location_option_id is used.
	if err := tx.Find(outtakeLocationOption, c.Param("outtake_location_option_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(outtakeLocationOption); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "outtakeLocationOption.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/outtake_location_options")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(outtakeLocationOption))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(outtakeLocationOption))
	}).Respond(c)
}
