package actions

import (
	"creaves/models"
	"fmt"
	"net/http"
	"strings"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/nulls"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Outtaketype)
// DB Table: Plural (outtaketypes)
// Resource: Plural (Outtaketypes)
// Path: Plural (/outtaketypes)
// View Template Folder: Plural (/templates/outtaketypes/)

// OuttaketypesResource is the resource for the Outtaketype model
type OuttaketypesResource struct {
	buffalo.Resource
}

// List gets all Outtaketypes. This function is mapped to the path
// GET /outtaketypes
func (v OuttaketypesResource) List(c buffalo.Context) error {
	// Maintainer only
	if _, err := requireMaintainer(c); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	outtaketypes := &models.Outtaketypes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Outtaketypes from the DB
	if err := q.All(outtaketypes); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("outtaketypes", outtaketypes)
		return c.Render(http.StatusOK, r.HTML("/outtaketypes/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(outtaketypes))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(outtaketypes))
	}).Respond(c)
}

// Show gets the data for one Outtaketype. This function is mapped to
// the path GET /outtaketypes/{outtaketype_id}
func (v OuttaketypesResource) Show(c buffalo.Context) error {
	// Maintainer only
	if _, err := requireMaintainer(c); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Outtaketype
	outtaketype := &models.Outtaketype{}

	// To find the Outtaketype the parameter outtaketype_id is used.
	if err := tx.Find(outtaketype, c.Param("outtaketype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("outtaketype", outtaketype)
		replacements := &models.Outtaketypes{}
		if err := tx.Where("id <> ?", outtaketype.ID).Order("name asc").All(replacements); err != nil {
			return err
		}
		c.Set("outtaketype_replacements", replacements)

		return c.Render(http.StatusOK, r.HTML("/outtaketypes/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(outtaketype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(outtaketype))
	}).Respond(c)
}

// setOuttaketypeRuleFormValues loads the native statuses and the currently
// excluded IDs so the form can render the multi-select with selection.
func setOuttaketypeRuleFormValues(c buffalo.Context, tx *pop.Connection, outtaketype *models.Outtaketype) error {
	nativeStatuses := &models.NativeStatuses{}
	if err := tx.Order("id asc").All(nativeStatuses); err != nil {
		return err
	}
	c.Set("nativeStatuses", nativeStatuses)
	excluded := map[string]bool{}
	for _, id := range outtaketype.ExcludedNativeStatusList() {
		excluded[id] = true
	}
	c.Set("excludedNativeStatuses", excluded)
	return nil
}

// bindExcludedNativeStatuses reads the multi-select values (name:
// excluded_native_status_ids) and stores them as a normalized CSV on the model.
func bindExcludedNativeStatuses(c buffalo.Context, outtaketype *models.Outtaketype) {
	if err := c.Request().ParseForm(); err != nil {
		return
	}
	ids := []string{}
	for _, id := range c.Request().Form["excluded_native_status_ids"] {
		id = strings.TrimSpace(id)
		if id != "" {
			ids = append(ids, id)
		}
	}
	if len(ids) == 0 {
		outtaketype.ExcludedNativeStatuses = nulls.String{}
		return
	}
	outtaketype.ExcludedNativeStatuses = nulls.NewString(strings.Join(ids, ","))
}

// New renders the form for creating a new Outtaketype.
// This function is mapped to the path GET /outtaketypes/new
func (v OuttaketypesResource) New(c buffalo.Context) error {
	// Maintainer only
	if _, err := requireMaintainer(c); err != nil {
		return err
	}

	c.Set("outtaketype", &models.Outtaketype{})

	tx := c.Value("tx").(*pop.Connection)
	if err := setTranslationValues(c, tx, "outtaketypes", "", []string{"name", "description", "discoverer_news"}); err != nil {
		return err
	}
	if err := setOuttaketypeRuleFormValues(c, tx, &models.Outtaketype{}); err != nil {
		return err
	}

	return c.Render(http.StatusOK, r.HTML("/outtaketypes/new.plush.html"))
}

// Create adds a Outtaketype to the DB. This function is mapped to the
// path POST /outtaketypes
func (v OuttaketypesResource) Create(c buffalo.Context) error {
	// Maintainer only
	if _, err := requireMaintainer(c); err != nil {
		return err
	}

	// Allocate an empty Outtaketype
	outtaketype := &models.Outtaketype{}

	// Bind outtaketype to the html form elements
	if err := c.Bind(outtaketype); err != nil {
		return err
	}
	bindExcludedNativeStatuses(c, outtaketype)

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(outtaketype)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("outtaketype", outtaketype)
			if err := setOuttaketypeRuleFormValues(c, tx, outtaketype); err != nil {
				return err
			}

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/outtaketypes/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	queuePostCommitInvalidation(c, InvalidateOuttaketypesRefCache)
	if err := saveTranslations(c, tx, "outtaketypes", outtaketype.ID.String(), []string{"name", "description", "discoverer_news"}); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "outtaketype.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/outtaketypes/%v", outtaketype.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(outtaketype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(outtaketype))
	}).Respond(c)
}

// Edit renders a edit form for a Outtaketype. This function is
// mapped to the path GET /outtaketypes/{outtaketype_id}/edit
func (v OuttaketypesResource) Edit(c buffalo.Context) error {
	// Maintainer only
	if _, err := requireMaintainer(c); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Outtaketype
	outtaketype := &models.Outtaketype{}

	if err := tx.Find(outtaketype, c.Param("outtaketype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("outtaketype", outtaketype)
	if err := setTranslationValues(c, tx, "outtaketypes", outtaketype.ID.String(), []string{"name", "description", "discoverer_news"}); err != nil {
		return err
	}
	if err := setOuttaketypeRuleFormValues(c, tx, outtaketype); err != nil {
		return err
	}

	return c.Render(http.StatusOK, r.HTML("/outtaketypes/edit.plush.html"))
}

// Update changes a Outtaketype in the DB. This function is mapped to
// the path PUT /outtaketypes/{outtaketype_id}
func (v OuttaketypesResource) Update(c buffalo.Context) error {
	// Maintainer only
	if _, err := requireMaintainer(c); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Outtaketype
	outtaketype := &models.Outtaketype{}

	if err := tx.Find(outtaketype, c.Param("outtaketype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Reset statuses
	outtaketype.Default = false
	outtaketype.Dead = false

	// Bind Outtaketype to the html form elements
	if err := c.Bind(outtaketype); err != nil {
		return err
	}
	bindExcludedNativeStatuses(c, outtaketype)

	verrs, err := tx.ValidateAndUpdate(outtaketype)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("outtaketype", outtaketype)
			if err := setOuttaketypeRuleFormValues(c, tx, outtaketype); err != nil {
				return err
			}

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/outtaketypes/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	queuePostCommitInvalidation(c, InvalidateOuttaketypesRefCache)
	if err := saveTranslations(c, tx, "outtaketypes", outtaketype.ID.String(), []string{"name", "description", "discoverer_news"}); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "outtaketype.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/outtaketypes/%v", outtaketype.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(outtaketype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(outtaketype))
	}).Respond(c)
}

// Destroy deletes a Outtaketype from the DB. This function is mapped
// to the path DELETE /outtaketypes/{outtaketype_id}
func (v OuttaketypesResource) Destroy(c buffalo.Context) error {
	// Maintainer only
	if _, err := requireMaintainer(c); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Outtaketype
	outtaketype := &models.Outtaketype{}

	// To find the Outtaketype the parameter outtaketype_id is used.
	if err := tx.Find(outtaketype, c.Param("outtaketype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}
	if replacementID := c.Param("replacement_id"); replacementID != "" {
		if err := referenceRemap(c, "outtaketypes", "outtaketype_id", map[string]string{"outtakes": "outtaketype_id"}); err != nil {
			return err
		}
		queuePostCommitInvalidation(c, InvalidateOuttaketypesRefCache)
		return nil
	}

	if err := tx.Destroy(outtaketype); err != nil {
		return err
	}
	queuePostCommitInvalidation(c, InvalidateOuttaketypesRefCache)

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "outtaketype.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/outtaketypes")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(outtaketype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(outtaketype))
	}).Respond(c)
}
