package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"creaves/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (SubsideGroup)
// DB Table: Plural (subside_groups)
// Resource: Plural (SubsideGroups)
// Path: Plural (/subside_groups)
// View Template Folder: Plural (/templates/subside_groups/)

// SubsideGroupsResource is the resource for the SubsideGroup model
type SubsideGroupsResource struct {
	buffalo.Resource
}

// List gets all SubsideGroups. This function is mapped to the path
// GET /subside_groups
func (v SubsideGroupsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	subsideGroups := &models.SubsideGroups{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all SubsideGroups from the DB
	if err := q.All(subsideGroups); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("subsideGroups", subsideGroups)
		return c.Render(http.StatusOK, r.HTML("subside_groups/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(subsideGroups))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(subsideGroups))
	}).Respond(c)
}

// Show gets the data for one SubsideGroup. This function is mapped to
// the path GET /subside_groups/{subside_group_id}
func (v SubsideGroupsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty SubsideGroup
	subsideGroup := &models.SubsideGroup{}

	// To find the SubsideGroup the parameter subside_group_id is used.
	if err := tx.Find(subsideGroup, c.Param("subside_group_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("subsideGroup", subsideGroup)

		return c.Render(http.StatusOK, r.HTML("subside_groups/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(subsideGroup))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(subsideGroup))
	}).Respond(c)
}

// New renders the form for creating a new SubsideGroup.
// This function is mapped to the path GET /subside_groups/new
func (v SubsideGroupsResource) New(c buffalo.Context) error {
	c.Set("subsideGroup", &models.SubsideGroup{})

	return c.Render(http.StatusOK, r.HTML("subside_groups/new.plush.html"))
}

// Create adds a SubsideGroup to the DB. This function is mapped to the
// path POST /subside_groups
func (v SubsideGroupsResource) Create(c buffalo.Context) error {
	// Allocate an empty SubsideGroup
	subsideGroup := &models.SubsideGroup{}

	// Bind subsideGroup to the html form elements
	if err := c.Bind(subsideGroup); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(subsideGroup)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("subsideGroup", subsideGroup)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("subside_groups/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "subsideGroup.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/subside_groups/%v", subsideGroup.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(subsideGroup))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(subsideGroup))
	}).Respond(c)
}

// Edit renders a edit form for a SubsideGroup. This function is
// mapped to the path GET /subside_groups/{subside_group_id}/edit
func (v SubsideGroupsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty SubsideGroup
	subsideGroup := &models.SubsideGroup{}

	if err := tx.Find(subsideGroup, c.Param("subside_group_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("subsideGroup", subsideGroup)
	return c.Render(http.StatusOK, r.HTML("subside_groups/edit.plush.html"))
}

// Update changes a SubsideGroup in the DB. This function is mapped to
// the path PUT /subside_groups/{subside_group_id}
func (v SubsideGroupsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty SubsideGroup
	subsideGroup := &models.SubsideGroup{}

	if err := tx.Find(subsideGroup, c.Param("subside_group_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind SubsideGroup to the html form elements
	if err := c.Bind(subsideGroup); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(subsideGroup)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("subsideGroup", subsideGroup)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("subside_groups/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "subsideGroup.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/subside_groups/%v", subsideGroup.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(subsideGroup))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(subsideGroup))
	}).Respond(c)
}

// Destroy deletes a SubsideGroup from the DB. This function is mapped
// to the path DELETE /subside_groups/{subside_group_id}
func (v SubsideGroupsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty SubsideGroup
	subsideGroup := &models.SubsideGroup{}

	// To find the SubsideGroup the parameter subside_group_id is used.
	if err := tx.Find(subsideGroup, c.Param("subside_group_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(subsideGroup); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "subsideGroup.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/subside_groups")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(subsideGroup))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(subsideGroup))
	}).Respond(c)
}
