package actions

import (
	"creaves/models"
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v5"
	"github.com/gobuffalo/x/responder"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Traveltype)
// DB Table: Plural (traveltypes)
// Resource: Plural (Traveltypes)
// Path: Plural (/traveltypes)
// View Template Folder: Plural (/templates/traveltypes/)

// TraveltypesResource is the resource for the Traveltype model
type TraveltypesResource struct {
	buffalo.Resource
}

// List gets all Traveltypes. This function is mapped to the path
// GET /traveltypes
func (v TraveltypesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	traveltypes := &models.Traveltypes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Traveltypes from the DB
	if err := q.Order("name desc").All(traveltypes); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("traveltypes", traveltypes)
		return c.Render(http.StatusOK, r.HTML("/traveltypes/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(traveltypes))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(traveltypes))
	}).Respond(c)
}

// Show gets the data for one Traveltype. This function is mapped to
// the path GET /traveltypes/{traveltype_id}
func (v TraveltypesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Traveltype
	traveltype := &models.Traveltype{}

	// To find the Traveltype the parameter traveltype_id is used.
	if err := tx.Find(traveltype, c.Param("traveltype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("traveltype", traveltype)

		return c.Render(http.StatusOK, r.HTML("/traveltypes/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(traveltype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(traveltype))
	}).Respond(c)
}

// New renders the form for creating a new Traveltype.
// This function is mapped to the path GET /traveltypes/new
func (v TraveltypesResource) New(c buffalo.Context) error {
	c.Set("traveltype", &models.Traveltype{})

	return c.Render(http.StatusOK, r.HTML("/traveltypes/new.plush.html"))
}

// Create adds a Traveltype to the DB. This function is mapped to the
// path POST /traveltypes
func (v TraveltypesResource) Create(c buffalo.Context) error {
	// Allocate an empty Traveltype
	traveltype := &models.Traveltype{}

	// Bind traveltype to the html form elements
	if err := c.Bind(traveltype); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(traveltype)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("traveltype", traveltype)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/traveltypes/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "traveltype.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/traveltypes/%v", traveltype.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(traveltype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(traveltype))
	}).Respond(c)
}

// Edit renders a edit form for a Traveltype. This function is
// mapped to the path GET /traveltypes/{traveltype_id}/edit
func (v TraveltypesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Traveltype
	traveltype := &models.Traveltype{}

	if err := tx.Find(traveltype, c.Param("traveltype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("traveltype", traveltype)
	return c.Render(http.StatusOK, r.HTML("/traveltypes/edit.plush.html"))
}

// Update changes a Traveltype in the DB. This function is mapped to
// the path PUT /traveltypes/{traveltype_id}
func (v TraveltypesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Traveltype
	traveltype := &models.Traveltype{}

	if err := tx.Find(traveltype, c.Param("traveltype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Traveltype to the html form elements
	if err := c.Bind(traveltype); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(traveltype)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("traveltype", traveltype)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/traveltypes/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "traveltype.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/traveltypes/%v", traveltype.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(traveltype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(traveltype))
	}).Respond(c)
}

// Destroy deletes a Traveltype from the DB. This function is mapped
// to the path DELETE /traveltypes/{traveltype_id}
func (v TraveltypesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Traveltype
	traveltype := &models.Traveltype{}

	// To find the Traveltype the parameter traveltype_id is used.
	if err := tx.Find(traveltype, c.Param("traveltype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(traveltype); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "traveltype.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/traveltypes")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(traveltype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(traveltype))
	}).Respond(c)
}
