package actions

import (
	"creaves/models"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/nulls"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/validate/v3"
	"github.com/gobuffalo/x/responder"
	"github.com/gofrs/uuid"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Treatment)
// DB Table: Plural (treatments)
// Resource: Plural (Treatments)
// Path: Plural (/treatments)
// View Template Folder: Plural (/templates/treatments/)

// TreatmentsResource is the resource for the Treatment model
type TreatmentsResource struct {
	buffalo.Resource
}

// To handle schedule forms
type treatmentSchedule struct {
	ScheduleRequiredMorning nulls.Bool
	ScheduleRequiredNoon    nulls.Bool
	ScheduleRequiredEvening nulls.Bool
	ScheduleStatusMorning   nulls.Bool
	ScheduleStatusNoon      nulls.Bool
	ScheduleStatusEvening   nulls.Bool
}

func (t *treatmentSchedule) String() string {
	jt, _ := json.Marshal(t)
	return string(jt)
}

// TreatmentUpdateSchedule (PUT /treatmentschedule) was removed with the
// care-plan migration (§8.3): treatment rows are read-only history;
// done-ticks live on the day plan (/care_plan/apply), the per-time entry
// toggle (POST /treatments/{tid}/entries/{eid}/toggle, bugs.md R5-3b) and
// the animal Plan tab.

// seedManualTreatmentEntries creates one pending entry per required bitmap
// bucket (bugs.md R5-3b, U25/D-e): the manual morning/noon/evening form
// seeds default times 08:00/12:00/18:00 — the per-time storage is the
// source of truth for manual treatments too.
func seedManualTreatmentEntries(tx *pop.Connection, t *models.Treatment) error {
	for _, bit := range []int{models.Treatement_MORNING, models.Treatement_NOON, models.Treatement_EVENING} {
		if t.Timebitmap&bit == 0 {
			continue
		}
		label := models.DefaultEntryTimes[bit]
		entry := &models.TreatmentTimeEntry{
			TreatmentID: t.ID,
			AnimalID:    t.AnimalID,
			DueAt:       entryDueAt(t.Date, label),
			TimeLabel:   label,
			Status:      models.TreatmentEntryStatusPending,
			Source:      models.TreatmentEntrySourceManual,
		}
		if err := tx.Create(entry); err != nil {
			return err
		}
	}
	return nil
}

// normalizeEntryLabel validates a HH:MM form label, falling back to def.
func normalizeEntryLabel(raw, def string) string {
	t := strings.TrimSpace(raw)
	if _, err := time.Parse("15:04", t); err != nil {
		return def
	}
	return t
}

// syncTreatmentEntryStatuses mirrors the edit form's 3-bucket checkboxes
// onto the per-time entries (bugs.md R5-3b, U25/D-e — Timedonebitmap is
// dormant). Required buckets rename their entry (editable per entry time,
// default 08:00/12:00/18:00) and set done/pending; un-required buckets
// drop their entries — same semantics as the retired bitmap bits. Entries
// created on a legacy row without entries carry source=migration.
func syncTreatmentEntryStatuses(tx *pop.Connection, treatment *models.Treatment, ts *treatmentSchedule, entryTimes map[int]string, now time.Time, userID uuid.UUID) error {
	buckets := []struct {
		bit  int
		req  nulls.Bool
		done nulls.Bool
		def  string
	}{
		{models.Treatement_MORNING, ts.ScheduleRequiredMorning, ts.ScheduleStatusMorning, models.DefaultEntryTimes[models.Treatement_MORNING]},
		{models.Treatement_NOON, ts.ScheduleRequiredNoon, ts.ScheduleStatusNoon, models.DefaultEntryTimes[models.Treatement_NOON]},
		{models.Treatement_EVENING, ts.ScheduleRequiredEvening, ts.ScheduleStatusEvening, models.DefaultEntryTimes[models.Treatement_EVENING]},
	}

	entries, err := loadTreatmentEntries(tx, treatment.ID)
	if err != nil {
		return err
	}

	for _, b := range buckets {
		if b.req.Bool {
			if err := upsertBucketEntry(tx, treatment, entries, entryTimes[b.bit], b.bit, b.done, now, userID); err != nil {
				return err
			}
			continue
		}
		if err := dropBucketEntries(tx, entries, entryTimes[b.bit], b.def); err != nil {
			return err
		}
	}
	return nil
}

// upsertBucketEntry renames (editable per entry time, bugs.md R5-3b) and
// statuses the entry of one required bucket, creating it when missing
// (legacy rows edited before the migration ran — source=migration).
func upsertBucketEntry(tx *pop.Connection, treatment *models.Treatment, entries models.TreatmentTimeEntries, rawLabel string, bit int, done nulls.Bool, now time.Time, userID uuid.UUID) error {
	def := models.DefaultEntryTimes[bit]
	label := normalizeEntryLabel(rawLabel, def)
	// Match the entry by any label it may carry: the form prefill
	// (possibly renamed by an earlier edit) or the bucket default.
	entry := entries.FindByLabel(label)
	if entry == nil && label != def {
		entry = entries.FindByLabel(def)
	}
	if entry == nil {
		entry = &models.TreatmentTimeEntry{
			TreatmentID: treatment.ID,
			AnimalID:    treatment.AnimalID,
			DueAt:       entryDueAt(treatment.Date, label),
			TimeLabel:   label,
			Status:      models.TreatmentEntryStatusPending,
			Source:      models.TreatmentEntrySourceMigration,
		}
		if err := tx.Create(entry); err != nil {
			return err
		}
	}
	entry.TimeLabel = label
	entry.DueAt = entryDueAt(treatment.Date, label)
	if done.Bool {
		entry.MarkDone(now, userID)
	} else {
		entry.Revert()
	}
	return tx.Update(entry)
}

// dropBucketEntries removes the entries of an un-required bucket — the
// bitmap-parity semantics of unchecking morning/noon/evening.
func dropBucketEntries(tx *pop.Connection, entries models.TreatmentTimeEntries, rawLabel, def string) error {
	label := normalizeEntryLabel(rawLabel, def)
	for i := range entries {
		e := &entries[i]
		if e.TimeLabel != label && e.TimeLabel != def {
			continue
		}
		if err := tx.Destroy(e); err != nil {
			return err
		}
	}
	return nil
}

// List gets all Treatments. This function is mapped to the path
// GET /treatments
func (v TreatmentsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	treatments := &models.Treatments{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Treatments from the DB
	if err := q.Eager().Order("date desc,timebitmap asc, animal_id desc").All(treatments); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("treatments", treatments)
		return c.Render(http.StatusOK, r.HTML("/treatments/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(treatments))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(treatments))
	}).Respond(c)
}

// Show gets the data for one Treatment. This function is mapped to
// the path GET /treatments/{treatment_id}
func (v TreatmentsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Treatment
	treatment := &models.Treatment{}

	// To find the Treatment the parameter treatment_id is used.
	if err := tx.Eager().Find(treatment, c.Param("treatment_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("treatment", treatment)
		// Back control + U16 label (bugs.md R5-2d/D-b): the care-plan card
		// links (dashboard + work screen) land here with ?back=... — the
		// chain collapses to the ORIGINAL origin so the label and the
		// landing agree (e.g. "Back to dashboard" → /).
		back := unwrapBackChain(safeBackParam(c))
		c.Set("back", back)
		c.Set("landingBackLabel", landingBackLabelKey(back))

		return c.Render(http.StatusOK, r.HTML("/treatments/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(treatment))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(treatment))
	}).Respond(c)
}

// New renders the form for creating a new Treatment.
// This function is mapped to the path GET /treatments/new
func (v TreatmentsResource) New(c buffalo.Context) error {
	tc := &models.TreatmentTemplate{
		Dates:   time.Now().Format(models.DateFormat),
		Morning: true,
		Noon:    true,
		Evening: true,
	}
	c.Set("treatmentTemplate", tc)

	animalYearNumber := c.Param("animal_year_number")
	if len(animalYearNumber) > 0 {
		// Get the DB connection from the context
		tx, ok := c.Value("tx").(*pop.Connection)
		if !ok {
			return fmt.Errorf("no transaction found")
		}

		animal := &models.Animal{}
		errCode := http.StatusOK

		// for message
		data := map[string]interface{}{
			"animalID": animalYearNumber,
		}

		c.Logger().Debug("animalYearNumber:", animalYearNumber)
		matches := AnimalYearNumberRegEx.FindStringSubmatch(animalYearNumber)
		if matches == nil {
			return fmt.Errorf("invalid year number: %s", animalYearNumber)
		}
		c.Logger().Debug("animalYearNumber regex matches:", matches)
		q := tx.Where("yearNumber = ?", matches[1])
		if len(matches) == 4 && len(matches[3]) == 2 {
			q = q.Where("year = ?", fmt.Sprintf("20%s", matches[3]))
		}

		err := q.Order("ID desc").First(animal)
		if err != nil {
			c.Flash().Add("danger", T.Translate(c, "treatment.animal.not.found", data))
			errCode = http.StatusNotFound
		}
		if animal.OuttakeID.Valid {
			c.Flash().Add("danger", T.Translate(c, "treatment.animal.outtake.already.exist", data))
			errCode = http.StatusConflict
		}

		if errCode != http.StatusOK {
			return c.Render(errCode, r.HTML("/treatments/new.plush.html"))
		}

		if _, err := EnrichAnimal(animal, c); err != nil {
			return err
		}

		tc.Animal = animal
		tc.AnimalID = animal.ID
	}

	return c.Render(http.StatusOK, r.HTML("/treatments/new.plush.html"))
}

// Create adds a Treatment to the DB. This function is mapped to the
// path POST /treatments
func (v TreatmentsResource) Create(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Treatment
	treatments := []*models.Treatment{}
	treatmentTemplate := &models.TreatmentTemplate{}

	// Bind treatment to the html form elements
	if err := c.Bind(treatmentTemplate); err != nil {
		return err
	}
	// Normalize possibly-localized drug input back to canonical (Option A)
	treatmentTemplate.Drug = resolveReferenceInput(c, "drugs", treatmentTemplate.Drug)
	// Wound-care treatment (issue #96): no medication and no posology, only
	// remarks. Store the canonical marker as Drug and clear the posology.
	if treatmentTemplate.NoDrug {
		treatmentTemplate.Drug = models.WoundCareDrugName
		treatmentTemplate.Dosage = ""
	}
	treatmentTemplate.Animal = &models.Animal{}
	if err := tx.Find(treatmentTemplate.Animal, treatmentTemplate.AnimalID); err != nil {
		c.Logger().Errorf("Animal id %d not found for %v", treatmentTemplate.AnimalID, treatmentTemplate)
		return c.Render(http.StatusUnprocessableEntity, r.HTML("/treatments/new.plush.html"))
	}
	c.Logger().Debugf("Binded treatmentTemplate with %v", treatmentTemplate)

	bitmap := models.TreatmentBoolToBitmap(
		treatmentTemplate.Morning,
		treatmentTemplate.Noon,
		treatmentTemplate.Evening,
	)

	for _, d := range strings.Split(treatmentTemplate.Dates, ",") {
		date, err := time.Parse(models.DateFormat, strings.TrimSpace(d))
		if err != nil {
			return err
		}

		t := &models.Treatment{
			Date:           date,
			AnimalID:       treatmentTemplate.AnimalID,
			Drug:           treatmentTemplate.Drug,
			Dosage:         treatmentTemplate.Dosage,
			Remarks:        treatmentTemplate.Remarks,
			Timebitmap:     bitmap,
			Timedonebitmap: 0,
		}
		treatments = append(treatments, t)
	}

	c.Logger().Debugf("Treatments: %v", treatments)

	// Save all, skipping entries that are exact duplicates of a treatment
	// created moments ago (double submission, issue #100).
	var verrs *validate.Errors
	var err error
	created := 0
	for _, treatment := range treatments {
		if recentDuplicateExists(c.Logger(), tx, &models.Treatment{}, treatmentFingerprintQuery,
			treatment.AnimalID, treatment.Date, treatment.Drug, treatment.Dosage, treatment.Remarks, treatment.Timebitmap, treatment.Timedonebitmap) {
			c.Logger().Warnf("Duplicate submission guard: skipping treatment already recorded for animal %d on %s", treatment.AnimalID, treatment.Date.Format(models.DateFormat))
			continue
		}
		// Validate the data from the html form
		verrs, err = tx.ValidateAndCreate(treatment)
		if err != nil {
			return err
		}
		if verrs.HasAny() {
			break
		}
		created++
		// bugs.md R5-3b (U25/D-e): seed the per-time entries for the
		// required buckets (default 08:00/12:00/18:00).
		if err := seedManualTreatmentEntries(tx, treatment); err != nil {
			return err
		}
		// Audit log: treatment creation (best effort)
		auditAnimalChange(c, tx, treatment.AnimalID, models.AuditEntityTreatment, auditEntityID(treatment.ID), models.AuditActionCreate, nil, auditTreatmentProjection(*treatment))
	}

	// Every entry of the submission was already recorded: the form was
	// double-submitted. Warn the user and redirect without creating anything.
	if created == 0 && len(treatments) > 0 && (verrs == nil || !verrs.HasAny()) {
		return duplicateSubmissionRedirect(c, "treatment.duplicate.prevented", "/animals/%v/#nav-treatment", treatmentTemplate.AnimalID)
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Logger().Debug("Errors: %v", verrs)
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("treatmentTemplate", treatmentTemplate)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/treatments/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "treatment.created.success"))
		if back := safeBackParam(c); back != "/" {
			// and redirect to the show page
			return c.Redirect(http.StatusSeeOther, back)
		}
		// and redirect to the animal page
		return c.Redirect(http.StatusSeeOther, "/animals/%v/#nav-treatment", treatmentTemplate.AnimalID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(treatments))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(treatments))
	}).Respond(c)
}

// Edit renders a edit form for a Treatment. This function is
// mapped to the path GET /treatments/{treatment_id}/edit
func (v TreatmentsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Treatment
	treatment := &models.Treatment{}

	if err := tx.Eager().Find(treatment, c.Param("treatment_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if _, err := EnrichAnimal(treatment.Animal, c); err != nil {
		return err
	}

	c.Set("treatment", treatment)
	return c.Render(http.StatusOK, r.HTML("/treatments/edit.plush.html"))
}

// Update changes a Treatment in the DB. This function is mapped to
// the path PUT /treatments/{treatment_id}
func (v TreatmentsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Treatment
	treatment := &models.Treatment{}

	if err := tx.Find(treatment, c.Param("treatment_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Audit snapshot before binding mutates the record.
	oldTreatment := *treatment

	// Bind Treatment to the html form elements
	if err := c.Bind(treatment); err != nil {
		return err
	}
	// Normalize possibly-localized drug input back to canonical (Option A)
	treatment.Drug = resolveReferenceInput(c, "drugs", treatment.Drug)

	// Decode schedule
	ts := &treatmentSchedule{}
	if err := c.Bind(ts); err != nil {
		return err
	}
	// Entry time labels (bugs.md R5-3b: editable per entry). The edit form
	// prefills the current label; empty/invalid inputs keep the defaults.
	entryTimes := &struct {
		Morning string
		Noon    string
		Evening string
	}{}
	if err := c.Bind(entryTimes); err != nil {
		return err
	}
	treatment.SetAllScheduleRequired(
		ts.ScheduleRequiredMorning.Bool,
		ts.ScheduleRequiredNoon.Bool,
		ts.ScheduleRequiredEvening.Bool)

	c.Logger().Debugf("Treatment Schedules: %v", ts)
	c.Logger().Debugf("Bitmap: req:%d (Timedonebitmap dormant since bugs.md U25 R5-3)", treatment.Timebitmap)

	verrs, err := tx.ValidateAndUpdate(treatment)
	if err != nil {
		return err
	}

	// Timedonebitmap is dormant (bugs.md U25/D-e): the done state is
	// mirrored onto the per-time entries (rename + done/pending sync).
	u := GetCurrentUser(c)
	var userID uuid.UUID
	if u != nil {
		userID = u.ID
	}
	if err := syncTreatmentEntryStatuses(tx, treatment, ts, map[int]string{
		models.Treatement_MORNING: entryTimes.Morning,
		models.Treatement_NOON:    entryTimes.Noon,
		models.Treatement_EVENING: entryTimes.Evening,
	}, time.Now(), userID); err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("treatment", treatment)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/treatments/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	// Audit log: treatment update (best effort)
	auditAnimalChange(c, tx, treatment.AnimalID, models.AuditEntityTreatment, auditEntityID(treatment.ID), models.AuditActionUpdate, auditTreatmentProjection(oldTreatment), auditTreatmentProjection(*treatment))

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "treatment.updated.success"))
		if back := safeBackParam(c); back != "/" {
			// and redirect to the show page
			return c.Redirect(http.StatusSeeOther, back)
		}
		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/treatments/%v", treatment.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(treatment))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(treatment))
	}).Respond(c)
}

// Destroy deletes a Treatment from the DB. This function is mapped
// to the path DELETE /treatments/{treatment_id}
func (v TreatmentsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Treatment
	treatment := &models.Treatment{}

	// To find the Treatment the parameter treatment_id is used.
	if err := tx.Find(treatment, c.Param("treatment_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(treatment); err != nil {
		return err
	}

	// Care-plan hook (§10-CP1): a destroyed fulfillment row is reported on
	// its care_plan_applications link instead of dangling.
	if err := MarkPlanApplicationFulfillmentDeleted(tx, models.ApplicationFulfillmentTreatment, treatment.ID.String()); err != nil {
		c.Logger().Warnf("care plan fulfillment_deleted hook: %v", err)
	}

	// Audit log: treatment deletion (best effort)
	auditAnimalChange(c, tx, treatment.AnimalID, models.AuditEntityTreatment, auditEntityID(treatment.ID), models.AuditActionDelete, auditTreatmentProjection(*treatment), nil)

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "treatment.destroyed.success"))
		if back := safeBackParam(c); back != "/" {
			// and redirect to the show page
			return c.Redirect(http.StatusSeeOther, back)
		}
		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/treatments")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(treatment))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(treatment))
	}).Respond(c)
}
