package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"creaves/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Zone)
// DB Table: Plural (zones)
// Resource: Plural (Zones)
// Path: Plural (/zones)
// View Template Folder: Plural (/templates/zones/)

// ZonesResource is the resource for the Zone model
type ZonesResource struct {
	buffalo.Resource
}

// List gets all Zones. This function is mapped to the path
// GET /zones
func (v ZonesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	zones := &models.Zones{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params()).Order("zone ASC")

	// Retrieve all Zones from the DB
	if err := q.All(zones); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("zones", zones)
		return c.Render(http.StatusOK, r.HTML("zones/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(zones))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(zones))
	}).Respond(c)
}

// Show gets the data for one Zone. This function is mapped to
// the path GET /zones/{zone_id}
func (v ZonesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Zone
	zone := &models.Zone{}

	// To find the Zone the parameter zone_id is used.
	if err := tx.Find(zone, c.Param("zone_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("zone", zone)

		return c.Render(http.StatusOK, r.HTML("zones/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(zone))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(zone))
	}).Respond(c)
}

// New renders the form for creating a new Zone.
// This function is mapped to the path GET /zones/new
func (v ZonesResource) New(c buffalo.Context) error {
	c.Set("zone", &models.Zone{})

	return c.Render(http.StatusOK, r.HTML("zones/new.plush.html"))
}

// Create adds a Zone to the DB. This function is mapped to the
// path POST /zones
func (v ZonesResource) Create(c buffalo.Context) error {
	// Allocate an empty Zone
	zone := &models.Zone{}

	// Bind zone to the html form elements
	if err := c.Bind(zone); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(zone)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("zone", zone)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("zones/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "zone.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/zones/%v", zone.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(zone))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(zone))
	}).Respond(c)
}

// Edit renders a edit form for a Zone. This function is
// mapped to the path GET /zones/{zone_id}/edit
func (v ZonesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Zone
	zone := &models.Zone{}

	if err := tx.Find(zone, c.Param("zone_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("zone", zone)
	return c.Render(http.StatusOK, r.HTML("zones/edit.plush.html"))
}

// Update changes a Zone in the DB. This function is mapped to
// the path PUT /zones/{zone_id}
func (v ZonesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Zone
	zone := &models.Zone{}

	if err := tx.Find(zone, c.Param("zone_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Zone to the html form elements
	if err := c.Bind(zone); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(zone)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("zone", zone)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("zones/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "zone.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/zones/%v", zone.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(zone))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(zone))
	}).Respond(c)
}

// Destroy deletes a Zone from the DB. This function is mapped
// to the path DELETE /zones/{zone_id}
func (v ZonesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Zone
	zone := &models.Zone{}

	// To find the Zone the parameter zone_id is used.
	if err := tx.Find(zone, c.Param("zone_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(zone); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "zone.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/zones")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(zone))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(zone))
	}).Respond(c)
}
