//go:generate goyacc -o dsl_yacc.go dsl.y
//go:generate rm -f y.output

// DSL implementation (§5.2 of docs/care-expert.md). No bespoke parser or
// lexer engine is used:
//
//   - The parser is GENERATED by goyacc (golang.org/x/tools/cmd/goyacc —
//     the x/tools extension, a known-good LALR engine) from the committed
//     grammar dsl.y. The generated dsl_yacc.go is a build artifact, NOT
//     committed: regenerate with `go generate ./models/careplan` (directives
//     above; needs goyacc on PATH — `go install
//     golang.org/x/tools/cmd/goyacc@latest`). The generated file is
//     self-contained (no x/tools runtime import at build time).
//   - The lexer is a thin adapter over the standard-library text/scanner
//     tokenizer, which supplies identifier/number/string recognition and
//     byte positions. The adapter adds only what is DSL-specific: the
//     two-character operators (<=, >=, !=, !~), case-insensitive keywords,
//     negative-number folding and the regex-safe string unquote — `\"` and
//     `\\` are the only escapes, any other backslash sequence passes through
//     verbatim so RE2 patterns like "\d{3}" or "\btiques\b" need no
//     double-escaping.
package careplan

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
	"text/scanner"
)

// Pos is a byte offset into the matcher expression source. Positions are
// stored 0-based and rendered as 1-based byte columns (Column) — the inline
// admin-UI error display uses these (§5.2: `weight_g < "abc"` → type error
// at col 12).
type Pos int

// Column renders p as the 1-based byte column shown in the admin UI.
func (p Pos) Column() int { return int(p) + 1 }

// LitKind discriminates the literal kinds the DSL accepts (§5.2).
type LitKind uint8

// Literal kinds.
const (
	LitString LitKind = iota
	LitNumber
	LitBool
)

// Literal is a DSL literal with its source position. Exactly one payload
// field is meaningful, per Kind.
type Literal struct {
	Kind LitKind
	Str  string
	Num  float64
	Bool bool
	Pos  Pos
}

// desc renders the literal for error messages.
func (l Literal) desc() string {
	switch l.Kind {
	case LitString:
		return strconv.Quote(l.Str)
	case LitNumber:
		return strconv.FormatFloat(l.Num, 'g', -1, 64)
	default:
		if l.Bool {
			return "true"
		}
		return "false"
	}
}

// fieldPos pairs a field/operator name with its source position — the
// grammar's union helper for T_IDENT and the comparison operators.
type fieldPos struct {
	name string
	pos  Pos
}

// Node is any AST node of the matcher expression grammar (§5.2).
type Node interface {
	nodePos() Pos
}

// OrNode is a disjunction: Left OR Right (lowest precedence).
type OrNode struct {
	Left, Right Node
	pos         Pos
}

func (n *OrNode) nodePos() Pos { return n.pos }

// AndNode is a conjunction: Left AND Right.
type AndNode struct {
	Left, Right Node
	pos         Pos
}

func (n *AndNode) nodePos() Pos { return n.pos }

// NotNode negates Expr (binds tighter than AND, §5.2).
type NotNode struct {
	Expr Node
	pos  Pos
}

func (n *NotNode) nodePos() Pos { return n.pos }

// PredicateNode is a binary predicate: Field Op Literal. It covers the
// comparison ops (=, !=, <, <=, >, >=), CONTAINS and the regex pair (~, !~);
// for the latter re holds the RE2 pattern compiled at validation time
// (§5.2: regex compiled once at parse time).
type PredicateNode struct {
	Field    string
	fieldPos Pos
	Op       string
	opPos    Pos
	Literal  Literal
	pos      Pos
	re       *regexp.Regexp
}

func (n *PredicateNode) nodePos() Pos { return n.pos }

// Regex returns the pattern compiled at validation time for ~/!~ — nil
// otherwise or before validation.
func (n *PredicateNode) Regex() *regexp.Regexp { return n.re }

// BetweenNode is a numeric range: Field BETWEEN Min AND Max (the AND is
// owned by BETWEEN, SQL-style, §5.2).
type BetweenNode struct {
	Field    string
	fieldPos Pos
	opPos    Pos
	Min      float64
	minPos   Pos
	Max      float64
	maxPos   Pos
	pos      Pos
}

func (n *BetweenNode) nodePos() Pos { return n.pos }

// InNode is a membership test: Field IN (l1, …, ln) or its case-insensitive
// variant Field INCI (…) (OpInCI). Op carries the exact DSL spelling — the
// trace and validation quote it; programmatic nodes may leave it empty (the
// evaluator then treats it as the plain CS IN).
type InNode struct {
	Field    string
	fieldPos Pos
	opPos    Pos
	Op       string
	Literals []Literal
	pos      Pos
}

func (n *InNode) nodePos() Pos { return n.pos }

// ParseError is a parse or semantic-validation error carrying the 1-based
// column for inline display next to the expression editor (§5.2).
type ParseError struct {
	Msg    string
	Column int
}

func (e *ParseError) Error() string { return fmt.Sprintf("col %d: %s", e.Column, e.Msg) }

// Parse parses expr to an AST without registry validation.
func Parse(expr string) (Node, error) { return parseWith(expr, nil) }

// ParseValidatedWith parses expr and runs the §5.2 save-time semantic
// validation against reg: fields must exist, ops must be declared by the
// field's provider, literal types must match the field type, IN () must be
// non-empty, BETWEEN bounds must be ordered and ~/!~ patterns must compile
// (RE2 — the compiled pattern is cached on the node). Returns *ParseError
// on failure.
func ParseValidatedWith(expr string, reg *Registry) (Node, error) {
	return parseWith(expr, reg)
}

func parseWith(expr string, reg *Registry) (Node, error) {
	l := &lexer{reg: reg}
	l.scan.Init(strings.NewReader(expr))
	l.scan.Error = func(s *scanner.Scanner, msg string) {
		if l.err == nil {
			l.err = &ParseError{Msg: msg, Column: s.Position.Offset + 1}
		}
	}
	if yyParse(l) != 0 && l.err == nil {
		l.err = &ParseError{Msg: "syntax error", Column: l.tokPos.Offset + 1}
	}
	if l.err != nil {
		return nil, l.err
	}
	if l.ast == nil {
		return nil, &ParseError{Msg: "invalid expression", Column: 1}
	}
	if reg != nil {
		if err := ValidateNode(l.ast, reg); err != nil {
			return nil, err
		}
	}
	return l.ast, nil
}

// ValidateNode runs the §5.2 semantic checks over an already-parsed AST
// (used at rule/matcher save time).
func ValidateNode(n Node, reg *Registry) error {
	switch t := n.(type) {
	case *OrNode:
		if err := ValidateNode(t.Left, reg); err != nil {
			return err
		}
		return ValidateNode(t.Right, reg)
	case *AndNode:
		if err := ValidateNode(t.Left, reg); err != nil {
			return err
		}
		return ValidateNode(t.Right, reg)
	case *NotNode:
		return ValidateNode(t.Expr, reg)
	case *PredicateNode:
		return validatePredicate(t, reg)
	case *BetweenNode:
		return validateBetween(t, reg)
	case *InNode:
		return validateIn(t, reg)
	}
	return nil
}

// litKindErr builds the "field %q expects a %s literal" type error at the
// literal's position (§5.2 col-exact type errors).
func litKindErr(field string, want LitKind, at Pos) *ParseError {
	name := map[LitKind]string{LitString: "string", LitNumber: "number", LitBool: "boolean"}[want]
	return &ParseError{Msg: fmt.Sprintf("field %q expects a %s literal", field, name), Column: at.Column()}
}

func validatePredicate(n *PredicateNode, reg *Registry) error {
	p, ok := reg.Get(n.Field)
	if !ok {
		return &ParseError{Msg: fmt.Sprintf("unknown field %q", n.Field), Column: n.fieldPos.Column()}
	}
	if !p.Allows(n.Op) {
		return &ParseError{Msg: fmt.Sprintf("field %q does not allow %q", n.Field, n.Op), Column: n.opPos.Column()}
	}
	switch p.Type {
	case TypeString:
		if n.Literal.Kind != LitString {
			return litKindErr(n.Field, LitString, n.Literal.Pos)
		}
		if n.Op == OpRegex || n.Op == OpNotRegex {
			re, err := regexp.Compile(n.Literal.Str) // RE2: no backtracking, ReDoS-safe (§5.1)
			if err != nil {
				return &ParseError{
					Msg:    fmt.Sprintf("field %q: invalid regular expression %q: %v", n.Field, n.Literal.Str, err),
					Column: n.Literal.Pos.Column(),
				}
			}
			n.re = re
		}
	case TypeNumber:
		if n.Literal.Kind != LitNumber {
			return litKindErr(n.Field, LitNumber, n.Literal.Pos)
		}
	case TypeBool:
		if n.Literal.Kind != LitBool {
			return litKindErr(n.Field, LitBool, n.Literal.Pos)
		}
	default:
		return &ParseError{Msg: fmt.Sprintf("field %q has unknown type %q", n.Field, p.Type), Column: n.fieldPos.Column()}
	}
	return nil
}

func validateBetween(n *BetweenNode, reg *Registry) error {
	p, ok := reg.Get(n.Field)
	if !ok {
		return &ParseError{Msg: fmt.Sprintf("unknown field %q", n.Field), Column: n.fieldPos.Column()}
	}
	if !p.Allows(OpBetween) {
		return &ParseError{Msg: fmt.Sprintf("field %q does not allow %q", n.Field, OpBetween), Column: n.opPos.Column()}
	}
	if n.Min > n.Max {
		return &ParseError{Msg: "BETWEEN lower bound must not exceed upper bound", Column: n.minPos.Column()}
	}
	return nil
}

func validateIn(n *InNode, reg *Registry) error {
	op := n.Op
	if op == "" { // programmatically built nodes default to the CS IN
		op = OpIn
	}
	p, ok := reg.Get(n.Field)
	if !ok {
		return &ParseError{Msg: fmt.Sprintf("unknown field %q", n.Field), Column: n.fieldPos.Column()}
	}
	if !p.Allows(op) {
		return &ParseError{Msg: fmt.Sprintf("field %q does not allow %q", n.Field, op), Column: n.opPos.Column()}
	}
	if len(n.Literals) == 0 {
		return &ParseError{Msg: "IN () needs at least one value", Column: n.opPos.Column()}
	}
	for _, lit := range n.Literals {
		want := LitString
		switch p.Type {
		case TypeNumber:
			want = LitNumber
		case TypeBool:
			want = LitBool
		}
		if lit.Kind != want {
			return litKindErr(n.Field, want, lit.Pos)
		}
	}
	return nil
}

// lexer adapts the standard-library text/scanner tokenizer to the goyacc
// yyLexer protocol expected by the generated parser (dsl_yacc.go).
type lexer struct {
	scan    scanner.Scanner
	reg     *Registry        // nil → parse without semantic validation
	ast     Node             // set by the grammar's start production
	err     *ParseError      // first error wins
	eofTok  bool             // explicit T_EOF already returned (see Lex)
	tokPos  scanner.Position // position of the token just returned
	tokText string           // text of the token just returned (error messages)
	lastTok int              // token id just returned (Error message shaping)
}

// Lex implements yyLexer: it returns the T_* token constants generated in
// dsl_yacc.go and fills the corresponding %union fields of lval (pos for
// keyword/operator tokens, lit for literals, fp for field identifiers).
func (l *lexer) Lex(lval *yySymType) (tokOut int) {
	tok := l.scan.Scan() // rune: scanner token or a single-rune DSL character
	l.tokPos = l.scan.Position
	l.tokText = l.scan.TokenText()
	defer func() { l.lastTok = tokOut }()

	pos := l.scan.Position
	at := Pos(pos.Offset)
	switch tok {
	case scanner.EOF:
		// dsl.y declares T_EOF as an explicit token (the premature-end
		// productions), so end-of-input is returned as T_EOF once; the
		// augmented grammar's own endmarker — which terminates the accept
		// check and error recovery — is signalled to yacc with 0 on any
		// subsequent call (yacc convention: Lex returns 0 at end of input).
		if l.eofTok {
			return 0
		}
		l.eofTok = true
		lval.pos = at
		return T_EOF
	case scanner.Ident:
		return l.ident(lval, l.tokText, at)
	case scanner.Int, scanner.Float:
		return l.number(lval, pos, 1)
	case scanner.String:
		raw := l.tokText
		if len(raw) < 2 || raw[len(raw)-1] != '"' {
			return l.fail(pos, "string literal not terminated")
		}
		lval.lit = Literal{Kind: LitString, Str: unquoteDSL(raw[1 : len(raw)-1]), Pos: at}
		return T_LSTR
	case scanner.Char, scanner.RawString:
		return l.fail(pos, fmt.Sprintf("unexpected token %s", strconv.Quote(l.tokText)))
	}

	switch tok { // single-rune tokens forwarded by the scanner
	case '(':
		return T_LPAREN
	case ')':
		return T_RPAREN
	case ',':
		return T_COMMA
	case '=':
		if l.scan.Peek() == '*' {
			l.scan.Next()
			l.tokText = "=*"
			return opTok(lval, OpEqCI, at, T_EQCI)
		}
		return opTok(lval, OpEq, at, T_EQ)
	case '<':
		if l.scan.Peek() == '=' {
			l.scan.Next()
			l.tokText = "<="
			return opTok(lval, OpLte, at, T_LE)
		}
		return opTok(lval, OpLt, at, T_LT)
	case '>':
		if l.scan.Peek() == '=' {
			l.scan.Next()
			l.tokText = ">="
			return opTok(lval, OpGte, at, T_GE)
		}
		return opTok(lval, OpGt, at, T_GT)
	case '~':
		return opTok(lval, OpRegex, at, T_TILDE)
	case '!':
		switch l.scan.Peek() {
		case '=':
			l.scan.Next()
			if l.scan.Peek() == '*' { // !=* — case-insensitive inequality
				l.scan.Next()
				l.tokText = "!=*"
				return opTok(lval, OpNeqCI, at, T_NEQCI)
			}
			l.tokText = "!="
			return opTok(lval, OpNeq, at, T_NEQ)
		case '~':
			l.scan.Next()
			l.tokText = "!~"
			return opTok(lval, OpNotRegex, at, T_NTILDE)
		}
		return l.fail(pos, "unexpected token '!'")
	case '-':
		if r := l.scan.Peek(); '0' <= r && r <= '9' {
			return l.number(lval, pos, -1)
		}
		return l.fail(pos, "unexpected token '-'")
	}
	return l.fail(pos, fmt.Sprintf("unexpected token %s", strconv.Quote(l.tokText)))
}

// opTok fills the <op> and <pos> union fields for an operator token — the
// grammar reads $n.op for the operator spelling that semantic validation and
// error messages quote verbatim (§5.2: `does not allow "="`).
func opTok(lval *yySymType, spell string, at Pos, tok int) int {
	lval.op = spell
	lval.pos = at
	return tok
}

// ident maps a keyword (case-insensitive per §5.2) or field identifier to
// its token, filling the pos / lit / fp union fields.
func (l *lexer) ident(lval *yySymType, w string, at Pos) int {
	switch {
	case strings.EqualFold(w, "AND"):
		lval.pos = at
		return T_AND
	case strings.EqualFold(w, "OR"):
		lval.pos = at
		return T_OR
	case strings.EqualFold(w, "NOT"):
		lval.pos = at
		return T_NOT
	case strings.EqualFold(w, "BETWEEN"):
		lval.pos = at
		return T_BETWEEN
	case strings.EqualFold(w, "IN"):
		lval.pos = at
		return T_IN
	case strings.EqualFold(w, "INCI"):
		lval.pos = at
		return T_INCI
	case strings.EqualFold(w, "CONTAINS"):
		return opTok(lval, OpContains, at, T_CONTAINS)
	case strings.EqualFold(w, "true"):
		lval.lit = Literal{Kind: LitBool, Bool: true, Pos: at}
		return T_TRUE
	case strings.EqualFold(w, "false"):
		lval.lit = Literal{Kind: LitBool, Bool: false, Pos: at}
		return T_FALSE
	}
	lval.fp = fieldPos{name: w, pos: at}
	return T_IDENT
}

// number folds an Int/Float scanner token into a T_LNUM literal; sign
// carries the folded unary minus ("weight_g > -5").
func (l *lexer) number(lval *yySymType, pos scanner.Position, sign float64) int {
	text := l.scan.TokenText()
	num, err := strconv.ParseFloat(text, 64)
	if err != nil {
		return l.fail(pos, fmt.Sprintf("invalid number %q", text))
	}
	l.tokText = text
	lval.lit = Literal{Kind: LitNumber, Num: sign * num, Pos: Pos(pos.Offset)}
	return T_LNUM
}

// Error implements yyLexer: the generated parser reports hard syntax errors
// here. The bare "syntax error" is rewritten with the offending token text
// (§5.2: precise, position-tagged messages for the admin UI).
func (l *lexer) Error(s string) {
	if l.err != nil {
		return
	}
	if s == "syntax error" {
		if l.lastTok == T_EOF {
			s = "unexpected end of expression"
		} else {
			s = "unexpected token " + l.tokText
		}
	}
	l.err = &ParseError{Msg: s, Column: l.tokPos.Offset + 1}
}

// errorAt records a grammar-action error from the malformed-input
// productions in dsl.y; the first error wins.
func (l *lexer) errorAt(p Pos, msg string) {
	if l.err != nil {
		return
	}
	l.err = &ParseError{Msg: msg, Column: p.Column()}
}

// regexPred builds the ~/!~ predicate node (grammar-action helper).
func (l *lexer) regexPred(fp fieldPos, opPos Pos, op string, lit Literal) Node {
	return &PredicateNode{
		Field:    fp.name,
		fieldPos: fp.pos,
		Op:       op,
		opPos:    opPos,
		Literal:  lit,
		pos:      fp.pos,
	}
}

// fail records a lexical error and returns T_EOF to unwind the parser;
// Parse reports l.err and later messages cannot overwrite the first one.
func (l *lexer) fail(pos scanner.Position, msg string) int {
	if l.err == nil {
		l.err = &ParseError{Msg: msg, Column: pos.Offset + 1}
	}
	return T_EOF
}

// unquoteDSL unquotes a string-literal body with the DSL rule that `\"` and
// `\\` are the only escapes (§5.2); any other backslash sequence passes
// through verbatim so RE2 patterns survive without double-escaping.
func unquoteDSL(body string) string {
	if !strings.ContainsRune(body, '\\') {
		return body
	}
	var b strings.Builder
	b.Grow(len(body))
	for i := 0; i < len(body); i++ {
		if body[i] == '\\' && i+1 < len(body) {
			switch body[i+1] {
			case '"':
				b.WriteByte('"')
				i++
				continue
			case '\\':
				b.WriteByte('\\')
				i++
				continue
			}
		}
		b.WriteByte(body[i])
	}
	return b.String()
}
