// Code generated by goyacc -o dsl_yacc.go dsl.y. DO NOT EDIT.

//line dsl.y:26

package careplan

import __yyfmt__ "fmt"

//line dsl.y:27

//line dsl.y:31
type yySymType struct {
	yys  int
	node Node
	lit  Literal
	lits []Literal
	op   string
	fp   fieldPos
	pos  Pos
}

const T_IDENT = 57346
const T_LSTR = 57347
const T_LNUM = 57348
const T_TRUE = 57349
const T_FALSE = 57350
const T_EQ = 57351
const T_NEQ = 57352
const T_LT = 57353
const T_LE = 57354
const T_GT = 57355
const T_GE = 57356
const T_TILDE = 57357
const T_NTILDE = 57358
const T_CONTAINS = 57359
const T_AND = 57360
const T_OR = 57361
const T_NOT = 57362
const T_BETWEEN = 57363
const T_IN = 57364
const T_LPAREN = 57365
const T_RPAREN = 57366
const T_COMMA = 57367
const T_EOF = 57368

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"T_IDENT",
	"T_LSTR",
	"T_LNUM",
	"T_TRUE",
	"T_FALSE",
	"T_EQ",
	"T_NEQ",
	"T_LT",
	"T_LE",
	"T_GT",
	"T_GE",
	"T_TILDE",
	"T_NTILDE",
	"T_CONTAINS",
	"T_AND",
	"T_OR",
	"T_NOT",
	"T_BETWEEN",
	"T_IN",
	"T_LPAREN",
	"T_RPAREN",
	"T_COMMA",
	"T_EOF",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 108

var yyAct = [...]int8{
	42, 44, 45, 46, 47, 18, 30, 31, 32, 33,
	34, 35, 27, 28, 29, 68, 53, 19, 25, 26,
	75, 77, 76, 49, 48, 50, 51, 17, 66, 44,
	45, 46, 47, 6, 69, 70, 67, 4, 20, 17,
	17, 17, 24, 9, 52, 74, 10, 16, 71, 39,
	43, 15, 14, 36, 73, 9, 9, 9, 10, 10,
	10, 3, 37, 22, 44, 45, 46, 47, 19, 17,
	7, 5, 78, 40, 13, 41, 12, 11, 79, 8,
	21, 2, 23, 72, 1, 9, 0, 0, 10, 0,
	0, 38, 44, 45, 46, 47, 62, 63, 64, 65,
	58, 59, 60, 61, 54, 55, 56, 57,
}

var yyPact = [...]int16{
	35, -32768, -21, -32768, -32768, -2, 20, -32768, -32768, 37,
	65, -32768, -32768, -32768, -32768, -32768, -3, -32768, -32768, 36,
	23, -32768, -32768, 49, 24, 18, -7, 99, 95, 91,
	-32768, -32768, -32768, -32768, -32768, -32768, 20, -32768, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, 10, -32768,
	-32768, -32768, -32768, 59, -32768, -32768, -32768, -32768, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, -32768, 39, -32768, -32768, -32768,
	-32768, -4, -32768, -32768, -32768, -32768, -32768, 87, -32768, -32768,
}

var yyPgo = [...]int8{
	0, 84, 81, 71, 33, 70, 79, 77, 76, 74,
	52, 51, 48, 0, 47, 42,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 2, 3, 3, 3, 4, 4,
	4, 5, 5, 5, 5, 5, 6, 6, 6, 6,
	6, 7, 7, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 9, 9, 9, 12, 12, 12, 10, 10,
	10, 10, 10, 10, 10, 10, 11, 11, 11, 11,
	14, 15, 15, 15, 15, 15, 15, 13, 13, 13,
	13,
}

var yyR2 = [...]int8{
	0, 2, 1, 1, 1, 1, 3, 3, 1, 3,
	3, 1, 2, 2, 3, 3, 1, 1, 1, 1,
	1, 3, 3, 5, 4, 4, 4, 4, 3, 3,
	3, 3, 5, 4, 5, 1, 3, 2, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1,
}

var yyChk = [...]int16{
	-32768, -1, -2, 26, 2, -3, -4, -5, -6, 20,
	23, -7, -8, -9, -10, -11, -14, 4, 26, 19,
	18, -5, 26, -3, -15, 21, 22, 15, 16, 17,
	9, 10, 11, 12, 13, 14, -4, 26, -5, 26,
	24, 26, -13, 26, 5, 6, 7, 8, 6, 5,
	7, 8, 26, 23, 5, 6, 7, 8, 5, 6,
	7, 8, 5, 6, 7, 8, 18, 26, 5, 24,
	25, -12, 24, -13, 6, 24, 26, 25, -13, -13,
}

var yyDef = [...]int8{
	0, -2, 0, 2, 3, 4, 5, 8, 11, 0,
	0, 16, 17, 18, 19, 20, 0, 50, 1, 0,
	0, 12, 13, 0, 0, 0, 0, 0, 0, 0,
	51, 52, 53, 54, 55, 56, 6, 7, 9, 10,
	14, 15, 21, 22, 57, 58, 59, 60, 0, 28,
	29, 30, 31, 0, 38, 40, 42, 44, 39, 41,
	43, 45, 46, 47, 48, 49, 0, 24, 25, 26,
	27, 0, 33, 35, 23, 32, 34, 0, 37, 36,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line dsl.y:58
		{
			yylex.(*lexer).ast = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:60
		{
			yylex.(*lexer).errorAt(yyDollar[1].pos, "unexpected end of expression")
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:62
		{
			yyVAL.node = nil
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:67
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:72
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:74
		{
			yyVAL.node = &OrNode{Left: yyDollar[1].node, Right: yyDollar[3].node, pos: yyDollar[2].pos}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:76
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "unexpected end of expression")
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:81
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:83
		{
			yyVAL.node = &AndNode{Left: yyDollar[1].node, Right: yyDollar[3].node, pos: yyDollar[2].pos}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:85
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "unexpected end of expression")
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:90
		{
			yyVAL.node = yyDollar[1].node
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line dsl.y:92
		{
			yyVAL.node = &NotNode{Expr: yyDollar[2].node, pos: yyDollar[1].pos}
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line dsl.y:94
		{
			yylex.(*lexer).errorAt(yyDollar[2].pos, "unexpected end of expression")
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:96
		{
			yyVAL.node = yyDollar[2].node
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:98
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "expected )")
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:111
		{
			yyVAL.node = &PredicateNode{
				Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos,
				Op: yyDollar[2].fp.name, opPos: yyDollar[2].fp.pos,
				Literal: yyDollar[3].lit,
				pos:     yyDollar[1].fp.pos,
			}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:120
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "unexpected end of expression")
		}
	case 23:
		yyDollar = yyS[yypt-5 : yypt+1]
//line dsl.y:125
		{
			yyVAL.node = &BetweenNode{
				Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos, opPos: yyDollar[2].pos,
				Min: yyDollar[3].lit.Num, minPos: yyDollar[3].lit.Pos,
				Max: yyDollar[5].lit.Num, maxPos: yyDollar[5].lit.Pos,
				pos: yyDollar[1].fp.pos,
			}
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line dsl.y:134
		{
			yylex.(*lexer).errorAt(yyDollar[4].pos, "expected AND")
		}
	case 25:
		yyDollar = yyS[yypt-4 : yypt+1]
//line dsl.y:136
		{
			yylex.(*lexer).errorAt(yyDollar[4].pos, "expected AND")
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line dsl.y:138
		{
			yylex.(*lexer).errorAt(yyDollar[4].pos, "expected AND")
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line dsl.y:140
		{
			yylex.(*lexer).errorAt(yyDollar[4].pos, "expected AND")
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:142
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "BETWEEN expects number bounds")
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:144
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "BETWEEN expects number bounds")
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:146
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "BETWEEN expects number bounds")
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:148
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "unexpected end of expression")
		}
	case 32:
		yyDollar = yyS[yypt-5 : yypt+1]
//line dsl.y:153
		{
			yyVAL.node = &InNode{
				Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos, opPos: yyDollar[2].pos,
				Literals: yyDollar[4].lits,
				pos:      yyDollar[1].fp.pos,
			}
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line dsl.y:161
		{
			yyVAL.node = &InNode{Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos, opPos: yyDollar[2].pos, pos: yyDollar[1].fp.pos}
		}
	case 34:
		yyDollar = yyS[yypt-5 : yypt+1]
//line dsl.y:165
		{
			yylex.(*lexer).errorAt(yyDollar[5].pos, "expected , or )")
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:170
		{
			yyVAL.lits = []Literal{yyDollar[1].lit}
		}
	case 36:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:172
		{
			yyVAL.lits = append(yyDollar[1].lits, yyDollar[3].lit)
		}
	case 37:
		yyDollar = yyS[yypt-2 : yypt+1]
//line dsl.y:174
		{
			yylex.(*lexer).errorAt(yyDollar[2].lit.Pos, "expected , or )")
			yyVAL.lits = yyDollar[1].lits
		}
	case 38:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:179
		{
			yyVAL.node = yylex.(*lexer).regexPred(yyDollar[1].fp, yyDollar[2].pos, OpRegex, yyDollar[3].lit)
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:181
		{
			yyVAL.node = yylex.(*lexer).regexPred(yyDollar[1].fp, yyDollar[2].pos, OpNotRegex, yyDollar[3].lit)
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:183
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:185
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:187
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:189
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:191
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:193
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:198
		{
			yyVAL.node = &PredicateNode{
				Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos,
				Op: yyDollar[2].op, opPos: yyDollar[2].pos,
				Literal: yyDollar[3].lit,
				pos:     yyDollar[1].fp.pos,
			}
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:207
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "CONTAINS expects a double-quoted string")
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:209
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "CONTAINS expects a double-quoted string")
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:211
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "CONTAINS expects a double-quoted string")
		}
	case 50:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:216
		{
			yyVAL.fp = yyDollar[1].fp
		}
	case 51:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:221
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 52:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:223
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:225
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:227
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:229
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:231
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:236
		{
			yyVAL.lit = yyDollar[1].lit
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:238
		{
			yyVAL.lit = yyDollar[1].lit
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:240
		{
			yyVAL.lit = yyDollar[1].lit
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:242
		{
			yyVAL.lit = yyDollar[1].lit
		}
	}
	goto yystack /* stack new state and value */
}
