// Code generated by goyacc -o dsl_yacc.go dsl.y. DO NOT EDIT.

//line dsl.y:26

package careplan

import __yyfmt__ "fmt"

//line dsl.y:27

//line dsl.y:31
type yySymType struct {
	yys  int
	node Node
	lit  Literal
	lits []Literal
	op   string
	fp   fieldPos
	pos  Pos
}

const T_IDENT = 57346
const T_LSTR = 57347
const T_LNUM = 57348
const T_TRUE = 57349
const T_FALSE = 57350
const T_EQ = 57351
const T_NEQ = 57352
const T_LT = 57353
const T_LE = 57354
const T_GT = 57355
const T_GE = 57356
const T_TILDE = 57357
const T_NTILDE = 57358
const T_CONTAINS = 57359
const T_EQCI = 57360
const T_NEQCI = 57361
const T_AND = 57362
const T_OR = 57363
const T_NOT = 57364
const T_BETWEEN = 57365
const T_IN = 57366
const T_INCI = 57367
const T_LPAREN = 57368
const T_RPAREN = 57369
const T_COMMA = 57370
const T_EOF = 57371

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"T_IDENT",
	"T_LSTR",
	"T_LNUM",
	"T_TRUE",
	"T_FALSE",
	"T_EQ",
	"T_NEQ",
	"T_LT",
	"T_LE",
	"T_GT",
	"T_GE",
	"T_TILDE",
	"T_NTILDE",
	"T_CONTAINS",
	"T_EQCI",
	"T_NEQCI",
	"T_AND",
	"T_OR",
	"T_NOT",
	"T_BETWEEN",
	"T_IN",
	"T_INCI",
	"T_LPAREN",
	"T_RPAREN",
	"T_COMMA",
	"T_EOF",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 127

var yyAct = [...]int8{
	77, 75, 31, 32, 35, 36, 37, 38, 28, 29,
	30, 33, 34, 18, 57, 72, 25, 26, 27, 47,
	48, 49, 50, 56, 19, 45, 47, 48, 49, 50,
	70, 52, 51, 53, 54, 20, 17, 73, 74, 71,
	6, 85, 83, 86, 47, 48, 49, 50, 81, 83,
	82, 4, 17, 17, 9, 55, 19, 80, 10, 78,
	39, 42, 43, 17, 44, 17, 24, 16, 46, 5,
	9, 9, 15, 14, 10, 10, 84, 40, 3, 84,
	23, 9, 13, 9, 87, 10, 12, 10, 22, 47,
	48, 49, 50, 47, 48, 49, 50, 7, 47, 48,
	49, 50, 66, 67, 68, 69, 11, 21, 8, 2,
	1, 79, 0, 0, 0, 76, 0, 0, 41, 62,
	63, 64, 65, 58, 59, 60, 61,
}

var yyPact = [...]int16{
	49, -32768, -16, -32768, -32768, 3, 15, -32768, -32768, 59,
	61, -32768, -32768, -32768, -32768, -32768, -7, -32768, -32768, 48,
	32, -32768, -32768, 35, 39, 26, -3, -12, 118, 114,
	97, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, 15,
	-32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768,
	-32768, 10, -32768, -32768, -32768, -32768, 88, 84, -32768, -32768,
	-32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768, -32768,
	51, -32768, -32768, -32768, -32768, 21, -32768, -32768, 14, -32768,
	-32768, -32768, -32768, 93, -32768, -32768, -32768, -32768,
}

var yyPgo = [...]int8{
	0, 110, 109, 69, 40, 97, 108, 106, 86, 82,
	73, 72, 1, 0, 67, 66,
}

var yyR1 = [...]int8{
	0, 1, 1, 1, 2, 3, 3, 3, 4, 4,
	4, 5, 5, 5, 5, 5, 6, 6, 6, 6,
	6, 7, 7, 8, 8, 8, 8, 8, 8, 8,
	8, 8, 9, 9, 9, 9, 9, 9, 12, 12,
	12, 10, 10, 10, 10, 10, 10, 10, 10, 11,
	11, 11, 11, 14, 15, 15, 15, 15, 15, 15,
	15, 15, 13, 13, 13, 13,
}

var yyR2 = [...]int8{
	0, 2, 1, 1, 1, 1, 3, 3, 1, 3,
	3, 1, 2, 2, 3, 3, 1, 1, 1, 1,
	1, 3, 3, 5, 4, 4, 4, 4, 3, 3,
	3, 3, 5, 4, 5, 5, 4, 5, 1, 3,
	2, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-32768, -1, -2, 29, 2, -3, -4, -5, -6, 22,
	26, -7, -8, -9, -10, -11, -14, 4, 29, 21,
	20, -5, 29, -3, -15, 23, 24, 25, 15, 16,
	17, 9, 10, 18, 19, 11, 12, 13, 14, -4,
	29, -5, 29, 27, 29, -13, 29, 5, 6, 7,
	8, 6, 5, 7, 8, 29, 26, 26, 5, 6,
	7, 8, 5, 6, 7, 8, 5, 6, 7, 8,
	20, 29, 5, 27, 28, -12, 27, -13, -12, 27,
	6, 27, 29, 28, -13, 27, 29, -13,
}

var yyDef = [...]int8{
	0, -2, 0, 2, 3, 4, 5, 8, 11, 0,
	0, 16, 17, 18, 19, 20, 0, 53, 1, 0,
	0, 12, 13, 0, 0, 0, 0, 0, 0, 0,
	0, 54, 55, 56, 57, 58, 59, 60, 61, 6,
	7, 9, 10, 14, 15, 21, 22, 62, 63, 64,
	65, 0, 28, 29, 30, 31, 0, 0, 41, 43,
	45, 47, 42, 44, 46, 48, 49, 50, 51, 52,
	0, 24, 25, 26, 27, 0, 33, 38, 0, 36,
	23, 32, 34, 0, 40, 35, 37, 39,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line dsl.y:59
		{
			yylex.(*lexer).ast = yyDollar[1].node
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:61
		{
			yylex.(*lexer).errorAt(yyDollar[1].pos, "unexpected end of expression")
		}
	case 3:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:63
		{
			yyVAL.node = nil
		}
	case 4:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:68
		{
			yyVAL.node = yyDollar[1].node
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:73
		{
			yyVAL.node = yyDollar[1].node
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:75
		{
			yyVAL.node = &OrNode{Left: yyDollar[1].node, Right: yyDollar[3].node, pos: yyDollar[2].pos}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:77
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "unexpected end of expression")
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:82
		{
			yyVAL.node = yyDollar[1].node
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:84
		{
			yyVAL.node = &AndNode{Left: yyDollar[1].node, Right: yyDollar[3].node, pos: yyDollar[2].pos}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:86
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "unexpected end of expression")
		}
	case 11:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:91
		{
			yyVAL.node = yyDollar[1].node
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line dsl.y:93
		{
			yyVAL.node = &NotNode{Expr: yyDollar[2].node, pos: yyDollar[1].pos}
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line dsl.y:95
		{
			yylex.(*lexer).errorAt(yyDollar[2].pos, "unexpected end of expression")
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:97
		{
			yyVAL.node = yyDollar[2].node
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:99
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "expected )")
		}
	case 21:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:112
		{
			yyVAL.node = &PredicateNode{
				Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos,
				Op: yyDollar[2].fp.name, opPos: yyDollar[2].fp.pos,
				Literal: yyDollar[3].lit,
				pos:     yyDollar[1].fp.pos,
			}
		}
	case 22:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:121
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "unexpected end of expression")
		}
	case 23:
		yyDollar = yyS[yypt-5 : yypt+1]
//line dsl.y:126
		{
			yyVAL.node = &BetweenNode{
				Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos, opPos: yyDollar[2].pos,
				Min: yyDollar[3].lit.Num, minPos: yyDollar[3].lit.Pos,
				Max: yyDollar[5].lit.Num, maxPos: yyDollar[5].lit.Pos,
				pos: yyDollar[1].fp.pos,
			}
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line dsl.y:135
		{
			yylex.(*lexer).errorAt(yyDollar[4].pos, "expected AND")
		}
	case 25:
		yyDollar = yyS[yypt-4 : yypt+1]
//line dsl.y:137
		{
			yylex.(*lexer).errorAt(yyDollar[4].pos, "expected AND")
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line dsl.y:139
		{
			yylex.(*lexer).errorAt(yyDollar[4].pos, "expected AND")
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line dsl.y:141
		{
			yylex.(*lexer).errorAt(yyDollar[4].pos, "expected AND")
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:143
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "BETWEEN expects number bounds")
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:145
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "BETWEEN expects number bounds")
		}
	case 30:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:147
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "BETWEEN expects number bounds")
		}
	case 31:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:149
		{
			yylex.(*lexer).errorAt(yyDollar[3].pos, "unexpected end of expression")
		}
	case 32:
		yyDollar = yyS[yypt-5 : yypt+1]
//line dsl.y:154
		{
			yyVAL.node = &InNode{
				Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos, opPos: yyDollar[2].pos,
				Op:       OpIn,
				Literals: yyDollar[4].lits,
				pos:      yyDollar[1].fp.pos,
			}
		}
	case 33:
		yyDollar = yyS[yypt-4 : yypt+1]
//line dsl.y:163
		{
			yyVAL.node = &InNode{Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos, opPos: yyDollar[2].pos, Op: OpIn, pos: yyDollar[1].fp.pos}
		}
	case 34:
		yyDollar = yyS[yypt-5 : yypt+1]
//line dsl.y:167
		{
			yylex.(*lexer).errorAt(yyDollar[5].pos, "expected , or )")
		}
	case 35:
		yyDollar = yyS[yypt-5 : yypt+1]
//line dsl.y:169
		{
			yyVAL.node = &InNode{
				Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos, opPos: yyDollar[2].pos,
				Op:       OpInCI,
				Literals: yyDollar[4].lits,
				pos:      yyDollar[1].fp.pos,
			}
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line dsl.y:178
		{
			yyVAL.node = &InNode{Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos, opPos: yyDollar[2].pos, Op: OpInCI, pos: yyDollar[1].fp.pos}
		}
	case 37:
		yyDollar = yyS[yypt-5 : yypt+1]
//line dsl.y:182
		{
			yylex.(*lexer).errorAt(yyDollar[5].pos, "expected , or )")
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:187
		{
			yyVAL.lits = []Literal{yyDollar[1].lit}
		}
	case 39:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:189
		{
			yyVAL.lits = append(yyDollar[1].lits, yyDollar[3].lit)
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line dsl.y:191
		{
			yylex.(*lexer).errorAt(yyDollar[2].lit.Pos, "expected , or )")
			yyVAL.lits = yyDollar[1].lits
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:196
		{
			yyVAL.node = yylex.(*lexer).regexPred(yyDollar[1].fp, yyDollar[2].pos, OpRegex, yyDollar[3].lit)
		}
	case 42:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:198
		{
			yyVAL.node = yylex.(*lexer).regexPred(yyDollar[1].fp, yyDollar[2].pos, OpNotRegex, yyDollar[3].lit)
		}
	case 43:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:200
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:202
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:204
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:206
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:208
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:210
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "regex patterns must be double-quoted strings")
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:215
		{
			yyVAL.node = &PredicateNode{
				Field: yyDollar[1].fp.name, fieldPos: yyDollar[1].fp.pos,
				Op: yyDollar[2].op, opPos: yyDollar[2].pos,
				Literal: yyDollar[3].lit,
				pos:     yyDollar[1].fp.pos,
			}
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:224
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "CONTAINS expects a double-quoted string")
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:226
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "CONTAINS expects a double-quoted string")
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line dsl.y:228
		{
			yylex.(*lexer).errorAt(yyDollar[3].lit.Pos, "CONTAINS expects a double-quoted string")
		}
	case 53:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:233
		{
			yyVAL.fp = yyDollar[1].fp
		}
	case 54:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:238
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 55:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:240
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:242
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:244
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:246
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:248
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:250
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:252
		{
			yyVAL.fp = fieldPos{name: yyDollar[1].op, pos: yyDollar[1].pos}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:257
		{
			yyVAL.lit = yyDollar[1].lit
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:259
		{
			yyVAL.lit = yyDollar[1].lit
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:261
		{
			yyVAL.lit = yyDollar[1].lit
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line dsl.y:263
		{
			yyVAL.lit = yyDollar[1].lit
		}
	}
	goto yystack /* stack new state and value */
}
